#!/bin/bash

if [ -z $1 ] ; then
	echo Syntax: cvsdiff dir
	exit 1
fi

DIR=`echo $1 | sed s?/CVS??`

echo dir $DIR

cat $DIR/CVS/Entries | awk -F / '{ print $2 }' | sort > /tmp/cvs.tmp
(cd $DIR && ls | sort | grep -v CVS > /tmp/dir.tmp)

comm -3 /tmp/cvs.tmp /tmp/dir.tmp

rm -f /tmp/cvs.tmp /tmp/dir.tmp

