#!/bin/bash

if ! test -f $1/core.mak ; then
	echo Syntax: stripsrc src
	exit 1
fi

if test -e $1.complete ; then
	echo $1.complete already exits
	exit 1
fi

mv $1 $1.complete

mkdir $1

LIST=`cat stripsrc.lst`

if test -e $1.complete/advance.pat ; then
	cp -a $1.complete/advance.pat $1
fi

for FILE in $LIST ; do
	cp -a $1.complete/$FILE $1/$FILE
done

