#!/bin/bash

if ! test -f $1/mame.mak ; then
	echo Syntax: stripmame src
	exit 1
fi

if test -e $1.complete ; then
	echo $1.complete already exits
	exit 1
fi

mv $1 $1.complete

mkdir $1
mkdir $1/cpu
mkdir $1/drivers
mkdir $1/includes
mkdir $1/machine
mkdir $1/sndhrdw
mkdir $1/sound
mkdir $1/vidhrdw

LIST=`cat stripmess.lst`

if test -e $1.complete/advance.pat ; then
	cp -a $1.complete/advance.pat $1
fi

for FILE in $LIST ; do
	cp -a $1.complete/$FILE $1/$FILE
done


