static void (* sharcdasm_table[256])(UINT32, UINT64) =
{
	// 0x00 - 0x0f
	dasm_idlenop,
	dasm_compute,
	dasm_immshift_dregdmpm_nodata,
	dasm_invalid,
	dasm_compute_modify,
	dasm_invalid,
	dasm_direct_jump,
	dasm_direct_jump,
	dasm_indirect_jump_compute,
	dasm_indirect_jump_compute,
	dasm_rts_compute,
	dasm_rts_compute,
	dasm_do_until_counter,
	dasm_do_until_counter,
	dasm_do_until,
	dasm_immmove_immdata_ureg,

	// 0x10 - 0x1f
	dasm_immmove_uregdmpm,
	dasm_immmove_uregdmpm,
	dasm_immmove_uregdmpm,
	dasm_immmove_uregdmpm,
	dasm_sysreg_bitop,
	dasm_immmove_uregdmpm,
	dasm_ireg_modify,
	dasm_misc,
	dasm_cjump_rframe,
	dasm_immmove_uregdmpm,
	dasm_immmove_uregdmpm,
	dasm_immmove_uregdmpm,
	dasm_immmove_uregdmpm,
	dasm_immmove_uregdmpm,
	dasm_immmove_uregdmpm,
	dasm_immmove_uregdmpm,

	// 0x20 - 0x2f
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,

	// 0x30 - 0x3f
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,
	dasm_compute_dreg_dmpm,

	// 0x40 - 0x4f
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,

	// 0x50 - 0x5f
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,
	dasm_compute_uregdmpm_regmod,

	// 0x60 - 0x6f
	dasm_compute_dregdmpm_immmod,
	dasm_compute_dregdmpm_immmod,
	dasm_compute_dregdmpm_immmod,
	dasm_compute_dregdmpm_immmod,
	dasm_compute_dregdmpm_immmod,
	dasm_compute_dregdmpm_immmod,
	dasm_compute_dregdmpm_immmod,
	dasm_compute_dregdmpm_immmod,
	dasm_compute_dregdmpm_immmod,
	dasm_compute_dregdmpm_immmod,
	dasm_compute_dregdmpm_immmod,
	dasm_compute_dregdmpm_immmod,
	dasm_compute_dregdmpm_immmod,
	dasm_compute_dregdmpm_immmod,
	dasm_compute_dregdmpm_immmod,
	dasm_compute_dregdmpm_immmod,

	// 0x70 - 0x7f
	dasm_compute_ureg_ureg,
	dasm_compute_ureg_ureg,
	dasm_compute_ureg_ureg,
	dasm_compute_ureg_ureg,
	dasm_compute_ureg_ureg,
	dasm_compute_ureg_ureg,
	dasm_compute_ureg_ureg,
	dasm_compute_ureg_ureg,
	dasm_compute_ureg_ureg,
	dasm_compute_ureg_ureg,
	dasm_compute_ureg_ureg,
	dasm_compute_ureg_ureg,
	dasm_compute_ureg_ureg,
	dasm_compute_ureg_ureg,
	dasm_compute_ureg_ureg,
	dasm_compute_ureg_ureg,

	// 0x80 - 0x8f
	dasm_immshift_dregdmpm,
	dasm_immshift_dregdmpm,
	dasm_immshift_dregdmpm,
	dasm_immshift_dregdmpm,
	dasm_immshift_dregdmpm,
	dasm_immshift_dregdmpm,
	dasm_immshift_dregdmpm,
	dasm_immshift_dregdmpm,
	dasm_immshift_dregdmpm,
	dasm_immshift_dregdmpm,
	dasm_immshift_dregdmpm,
	dasm_immshift_dregdmpm,
	dasm_immshift_dregdmpm,
	dasm_immshift_dregdmpm,
	dasm_immshift_dregdmpm,
	dasm_immshift_dregdmpm,

	// 0x90 - 0x9f
	dasm_immmove_immdata_dmpm,
	dasm_immmove_immdata_dmpm,
	dasm_immmove_immdata_dmpm,
	dasm_immmove_immdata_dmpm,
	dasm_immmove_immdata_dmpm,
	dasm_immmove_immdata_dmpm,
	dasm_immmove_immdata_dmpm,
	dasm_immmove_immdata_dmpm,
	dasm_immmove_immdata_dmpm,
	dasm_immmove_immdata_dmpm,
	dasm_immmove_immdata_dmpm,
	dasm_immmove_immdata_dmpm,
	dasm_immmove_immdata_dmpm,
	dasm_immmove_immdata_dmpm,
	dasm_immmove_immdata_dmpm,
	dasm_immmove_immdata_dmpm,

	// 0xa0 - 0xaf
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,

	// 0xb0 - 0xbf
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,
	dasm_immmove_uregdmpm_indirect,

	// 0xc0 - 0xcf
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,

	// 0xd0 - 0xdf
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,

	// 0xe0 - 0xef
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,

	// 0xf0 - 0xff
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
	dasm_indirect_jump_compute_dregdm,
};
