.TH "AdvanceMAME Joystick Tester" 1
.SH NAME
advj \(hy AdvanceMAME Joystick Tester
.SH SYNOPSIS 
advj [\(hydevice_joystick DEVICE] [\(hylog] [\(hylogsync]
.PD 0
.PP
.PD
.SH DESCRIPTION 
The \(oqadvj\(cq utility calibrates and tests the joystick.
.PP
The calibration data is not saved in the AdvanceMAME
configuration file. You must repeat the calibration process
in the emulator.
.PP
Check the \(oqadvdev.txt\(cq file for the description of the
\(oqdevice_joystick\(cq option.
.SH COPYRIGHT 
This file is Copyright (C) 2003 Andrea Mazzoleni.
