.TH "AdvanceMAME Keyboard Tester" 1
.SH NAME
advk \(hy AdvanceMAME Keyboard Tester
.SH SYNOPSIS 
advk [\(hydevice_keyboard DEVICE] [\(hylog] [\(hylogsync]
.PD 0
.PP
.PD
.SH DESCRIPTION 
The \(oqadvk\(cq utility shows the set of keys pressed at any time.
It can be used for detecting the keys available for \(oqadvmame\(cq
and \(oqadvmenu\(cq. It can also be used for detecting the keys
that have the \(a"ghost effect\(a".
.PP
The utility prints the number of keys pressed in \(oq[]\(cq and the
list of key codes detected.
.PP
Check the \(oqadvdev.txt\(cq file for the description of the
\(oqdevice_keyboard\(cq option.
.SH COPYRIGHT 
This file is Copyright (C) 2003 Andrea Mazzoleni, Filipe Estima,
Randy Schnedler.
