.TH "AdvanceMAME Mouse Tester" 1
.SH NAME
advm \(hy AdvanceMAME Mouse Tester
.SH SYNOPSIS 
advm [\(hydevice_mouse DEVICE] [\(hylog] [\(hylogsync]
.PD 0
.PP
.PD
.SH DESCRIPTION 
The \(oqadvm\(cq utility tests the mouse.
.PP
Check the \(oqadvdev.txt\(cq file for the description of the
\(oqdevice_mouse\(cq and related options.
.PP
In Linux you need to kill GPM before running \(oqadvm\(cq. Otherwise
the mouse may not respond correctly.
.SH COPYRIGHT 
This file is Copyright (C) 2003 Andrea Mazzoleni.
