.TH "AdvanceMAME/MESS Emulator" 1
.SH NAME
advmame, advmess \(hy AdvanceMAME/MESS Emulator
.SH SYNOPSIS 
advmame GAME [\(hydefault] [\(hyremove] [\(hycfg FILE]
.PD 0
.PP
.PD
	[\(hylog] [\(hylistxml] [\(hyrecord FILE] [\(hyplayback FILE]
.PD 0
.PP
.PD
	[\(hyversion] [\(hyhelp]
.PD 0
.PP
.PD
.PP
advmess MACHINE [images...] [\(hydefault] [\(hyremove] [\(hycfg FILE]
.PD 0
.PP
.PD
	[\(hylog] [\(hylistxml] [\(hyrecord FILE] [\(hyplayback FILE]
.PD 0
.PP
.PD
	[\(hyversion] [\(hyhelp]
.PD 0
.PP
.PD
.SH DESCRIPTION 
AdvanceMAME is an unofficial MAME version for GNU/Linux, Mac OS
X, DOS and Windows with an advanced video support for helping the
use with TVs, Arcade Monitors, Fixed Frequencies Monitors and
also with normal PC Monitors.
.PP
The major features are:
.PD 0
.IP \(bu
Automatic creation of \(oqperfect\(cq video modes with the correct
size and clock.
.IP \(bu
A lot of video boards supported for direct hardware registers
programming. (see the card*.txt files)
.IP \(bu
Support for 8, 15, 16 and 32 bits video modes.
.IP \(bu
Real hardware scanlines.
.IP \(bu
Software video image stretching by fractional factors, for
example to play vertical games like \(a"Pac\(hyMan\(a" with
horizontal Arcade Monitors or TVs.
.IP \(bu
Special \(oqscalex\(cq, \(oqscalek\(cq, \(oqlq\(cq, \(oqhq\(cq, and \(oqxbr\(cq effects to improve the aspect
with modern PC Monitors.
.IP \(bu
Special \(oqblit\(cq effects to improve the image quality in
stretching.
.IP \(bu
Special \(oqrgb\(cq effects to simulate the aspect of a real Arcade
Monitor.
.IP \(bu
Change of the video mode and other video options at runtime.
.IP \(bu
Support of Symmetric Multi\(hyProcessing (SMP) with a multiple
thread architecture (only for Linux).
.IP \(bu
Sound and video recording in WAV, PNG and MNG files.
.IP \(bu
Multiple mice support in Linux, DOS, Windows 2000 and Windows XP.
.IP \(bu
Automatic exit after some time of inactivity.
.IP \(bu
Scripts capabilities to drive external hardware devices
like LCDs and lights.
.IP \(bu
Textual configuration files.
.IP \(bu
Help screen describing the user input keys.
.PD
.SH KEYS 
In the game play you can use the following keys:
.RS 4
.PD 0
.HP 4
.I ESC
Exit.
.HP 4
.I F1
Help.
.HP 4
.I TAB
Main Menu.
.HP 4
.I F2
Test/Service Switch.
.HP 4
.I F3
Reset the game.
.HP 4
.I F7
Load a game state.
.HP 4
.I SHIFT + F7
Save a gam state.
.HP 4
.I F8
Decrease the frame skip value.
.HP 4
.I F9
Increase the frame skip value.
.HP 4
.I F10
Speed throttle.
.HP 4
.I F11
Display the frame per second.
.HP 4
.I F12
Save a snapshot.
.HP 4
.I P
Pause.
.HP 4
.I PAD *
Turbo mode until pressed.
.HP 4
.I PAD /
Cocktail mode (flip the screen vertically).
.HP 4
.I PAD
\(hy Mark the current time as the startup time of the game.
.HP 4
.I CTRL + ENTER
Start the sound and video recording.
.HP 4
.I ENTER
Stop the sound and video recording.
.HP 4
.I ,
Previous video mode.
.HP 4
.I .
Next video mode.
.HP 4
.I TILDE
Volume Menu.
.PD
.RE
.PP
for player 1 you can use the keys:
.RS 4
.PD 0
.HP 4
.I 1
Play.
.HP 4
.I 5
Insert coin.
.HP 4
.I ARROW
Move.
.HP 4
.I CTRL
First button.
.HP 4
.I ALT
Second button.
.HP 4
.I SPACE
Third button.
.PD
.RE
.PP
for player 2 you can use the keys:
.RS 4
.PD 0
.HP 4
.I 2
Play.
.HP 4
.I 6
Insert coin.
.HP 4
.I R, F, D, G
Move.
.HP 4
.I A
First button.
.HP 4
.I S
Second button.
.HP 4
.I Q
Third button.
.PD
.RE
.PP
for AdvanceMESS are available also the following keys:
.RS 4
.PD 0
.HP 4
.I ScrollLock
Switch to partial keyboard emulation
which lets you use keys like TAB, ALT and
CTRL.
.PD
.RE
.SH OPTIONS 
This is the list of the available command line options:
.TP
.B GAME/MACHINE
The game or machine to emulate. If the specified
GAME/MACHINE is unknown, a list of possible \(oqguesses\(cq
is printed.
.TP
.B \(hydefault
Add to the configuration file all the missing options
with default values.
.TP
.B \(hyremove
Remove from the configuration file all the options
with default values.
.TP
.B \(hycfg FILE
Select an alternate configuration file. In Linux and Mac
OS X the you can prefix the file name with \(a"./\(a" to
load it from the current directory.
.TP
.B \(hylog
A very detailed log of operations is saved in
a \(oq.log\(cq file. Very useful for debugging problems.
.TP
.B \(hylistxml
Outputs the internal MAME database in XML format.
.TP
.B \(hyrecord FILE
Record all the game inputs in the specified file.
The file is saved in the directory specified by the
\(oqdir_inp\(cq configuration option.
.TP
.B \(hyplayback FILE
Play back the previously recorded game inputs in the
specified file.
.TP
.B \(hyversion
Print the version number, the low\(hylevel device drivers
supported and the configuration directories.
.TP
.B \(hyhelp
Print a short command line help.
.PP
On the command line you can also specify all configuration
options with the format \(hyOPTION ARGUMENT. For boolean options
you don\(cqt need to specify the argument but you must use the
\(hyOPTION or \(hynoOPTION format. For example:
.PP
.RS 4
advmame pacman \(hydevice_sound sb \(hynodisplay_scanlines
.PD 0
.PP
.PD
.RE
.PP
You can use short options if they are unambiguous. You can remove
any prefix tag separated with \(oq_\(cq or truncate it.
For example \(oq\(hydev_cartdrige\(cq can be written as \(oq\(hydev_cart\(cq,
\(oq\(hycartdrige\(cq, \(oq\(hycart\(cq, ...
.PP
In Linux and Mac OS X you can also use \(oq\(hy\(hy\(cq before options instead of \(oq\(hy\(cq.
In DOS and Windows you can also use \(oq/\(cq.
.SH FEATURES 
This section contains a brief description of all the features
of AdvanceMAME.
.SS Automatic Video Mode Generation 
AdvanceMAME has the ability to directly control your video
board to get the best possible video modes with always the
correct size and aspect ratio.
.PP
You can control how the video modes are generated with the
\(oqdisplay_adjust\(cq option. More details are in the \(oqinstall.txt\(cq
file.
.SS Video Menu 
AdvanceMAME adds a new \(oqVideo\(cq menu in MAME to change the video
options.
.PP
You can select the desired video mode, the resize type and the
video effects.
.PP
The selected option is displayed at the right side of the menu,
the effective value used for the option is displayed in \(oq[]\(cq.
.SS Resize 
AdvanceMAME supports many software stretching types of the
game image. Generally they are not used, because a video
mode of the correct size is automatically generated.
But in some conditions it isn\(cqt possible, in this case the
image is stretched.
.PP
There are four stretch types: \(oqnone\(cq, \(oqinteger\(cq, \(oqmixed\(cq, \(oqfractional\(cq.
You can control the type of stretching with the \(oqdisplay_resize\(cq option.
.PP
The \(oqnone\(cq option simply disables any type of stretching.
The \(oqinteger\(cq option allows only integer stretching in the
horizontal and vertical directions. For example 1x2, 2x1, 2x2.
The \(oqmixed\(cq option allows integer stretching in the horizontal
direction and fractional stretching in the vertical direction.
For example 1x1.23, 2x1.18.
The \(oqfractional\(cq option allows fractional stretching in any
directions. For example 1.08x1.08, 1.34x1.78.
.PP
Usually the best choice is the \(oqmixed\(cq option. It\(cqs very fast
and the image quality doesn\(cqt suffer too much.
.SS Blit Effects 
AdvanceMAME supports many special video effects to improve
the image quality when it\(cqs stretched.
.PP
There are a lot of video effects: \(oqnone\(cq, \(oqmax\(cq, \(oqmean\(cq,
\(oqfilter\(cq, \(oqscalex\(cq, \(oqscalek\(cq, \(oqlq\(cq, \(oqhq\(cq and \(oqxbr\(cq.
You can select the favorite effect with the \(oqdisplay_resizeeffect\(cq
option, or from the runtime menu.
.PP
The \(oqnone\(cq effect simply duplicates and removes rows and lines
when the image is stretched.
The \(oqmax\(cq effect tries to save the image details checking the luminosity
of the pixels in stretching. It ensures to have vertical and horizontal lines
always of the same thickness.
The \(oqmean\(cq effect tries to save the image details displaying the
mean color of the pixels in stretching.
The \(oqfilter\(cq effect applies a generic blur filter computing the
mean color in the horizontal and vertical directions. The best
results are when the image is stretched almost by a double
factor. When the image is enlarged the filter is applied after
stretching; when reduced, it\(cqs applied before.
The \(oqscalex\(cq, \(oqscalek\(cq, \(oqlq\(cq, \(oqhq\(cq and \(oqxbr\(cq effects add missing pixels
trying to match the image patterns.
.PP
The \(oqscalex\(cq, \(oqscalek\(cq, \(oqlq\(cq, \(oqhq\(cq and \(oqxbr\(cq effects work only if the image is
magnified. To enable it you should also use the \(oqmagnify\(cq option.
.SS RGB Effects 
AdvanceMAME supports also some special video effects to simulate
the aspect of the game as displayed in an old fashion Arcade
Monitor.
.PP
You can simulate the RGB triads of the screen or the vertical and
horizontal scanlines.
.SS Mode Selection 
In the \(oqVideo Mode\(cq submenu you can select the favorite video
mode.
.PP
If you choose \(oqauto\(cq, the best video mode is chosen
automatically.
.PP
You can change the active video mode pressing \(oq,\(cq and \(oq.\(cq when
in game play.
.PP
You can force a specific video mode with the option
\(oqdisplay_mode\(cq.
.SS Per game/resolution/frequency/orientation options 
All the options are customizable in the configuration file for
the single game or for a subset of games defined by the game
resolution, frequency and orientation.
.SS Scripts 
AdvanceMAME supports a basic script language capable to
control an external hardware through the parallel port
or keyboard led signals.
.PP
More details are in the \(oqscript.txt\(cq file.
.SS Aspect Ratio Control 
AdvanceMAME tries always to display the game with the
correct aspect ratio.
.PP
But if you want, you can permit a small aspect error
to enlarge the effective game image on the screen.
It\(cqs very useful to display vertical games on
horizontal monitors and vice versa.
.PP
More details are in the description of the \(oqdisplay_expand\(cq
option.
.SS Speed Control 
AdvanceMAME permits a special speed control of the game
play.
.PP
You can play the game in a faster way, change arbitrarily the
frame rate, skip the game startup process at the maximum speed,
or skip the game animations pressing a key.
.PP
Press \(oqasterisk_pad\(cq to enable the \(oqturbo\(cq mode. Press \(oqminus_pad\(cq
to mark the time of the real game start. The next time the game is
started, it will execute very fast until this time.
.PP
More details are in the description of the \(oqsync_fps\(cq, \(oqsync_speed\(cq,
\(oqsync_turbospeed\(cq and \(oqsync_startuptime\(cq options.
.PP
The video and audio synchronization uses an advanced algorithm,
which ensure always the best performance.
.PP
The program continuously measures the time required to compute a
frame and continuously adapt the number of frame to skip and
to draw.
.PP
If it detects that you have system too slow to play the game
at full speed, it automatically disables any frame skipping.
.PP
If the underline Operand System allows that, AdvanceMAME release
the CPU when it isn\(cqt used after computing each frame reducing the
CPU occupation.
.SS Audio Control 
The audio volume is automatically adjusted to ensure
that all the emulated games have the same volume power.
.PP
An equalizer and a spectrum analyzer are also available.
.PP
More details are in the description of the \(oqsound_normalize\(cq
and \(oqsound_equalizer\(cq options.
.SS Exit Control 
If you have a real Arcade Cabinet you can configure AdvanceMAME
to automatically exit after some time of inactivity to save
your monitor screen.
.PP
For some supported games you can force the display of an
exit menu during the game play to prevent unwanted exit.
.PP
More details are in the description of the \(oqmisc_safequit\(cq,
and \(oqinput_idleexit\(cq options.
.SS Input Control 
AdvanceMAME supports a very fine control of the mapping
of the analog and digital inputs. You can remap any input
event using easy to maintain text configuration files.
.PP
More details are in the description of the \(oqinput_map\(cq
option.
.SS Audio and Video Recording 
AdvanceMAME can saves the game play in .WAV audio files and
.MNG video files.
.PP
More details are in the description of the \(oqrecord_*\(cq
options.
.SS User Interface 
AdvanceMAME displays the user interface directly on the screen
instead on the game image.
.PP
This means that the interface doesn\(cqt have applied the same video
effects of the game, it isn\(cqt limited on the game area, it
isn\(cqt recorded on video clips and you can customize the font.
.PP
Also, True Type fonts with alpha blending are supported.
.PP
More details are in the description of the \(oqui_*\(cq options.
.SS Input Help 
AdvanceMAME is able to display a help image containing the
input mapping of the emulated game. Any input element has a
different depending on the assigned player and if it\(cqs pressed
or not.
.PP
The default image is a standard keyboard, with the used keys
highlighted. If you have an Arcade cabinet you can create your
personalized control image and select each region to highlight.
.PP
Press \(oqf1\(cq on the game play to display it.
.PP
More details are in the description of the \(oqui_help*\(cq options.
.SS Input Text Configuration File 
All the user customizations are stored in a single textual
configuration file and not in a lot of .cfg file like other MAME ports.
.PP
This allows to view, edit and copy any customization manually.
They are also more compact because only the difference from the
default is saved.
.PP
They are independent of the internal MAME structure, so, when it
changes, you don\(cqt lose the customizations.
.PP
More details are in the description of the \(oqinput_setting\(cq,
\(oqinput_dipswitch\(cq, \(oqinput_configswitch\(cq options.
.SS Cocktail 
For cocktail arcade cabinets you can manually flip vertically the
screen for games without cocktail support.
.PP
Press \(oqslash_pad\(cq to flip the screen.
.SS Dipswitches Control 
You can customize with specialized options the game difficulty and
the game freeplay. These options are smart enough to solve
common ambiguities and errors in the game dipswitches definitions.
.PP
More details are in the description of the \(oqmisc_diffucilty\(cq and
\(oqmisc_freeplay\(cq options.
.SS LCD Panel 
AdvanceMAME is able to talk to an \(oqlcdproc\(cq server located anywhere
in internet to display arbitrary information on a real or simulated
LCD panel.
.SH USE CASES 
This section describes some useful cases for AdvanceMAME
on different video hardware.
.SS With a LCD Monitor 
On a LCD Monitor, AdvanceMAME is able to use the hardware
acceleration of your video board to stretch the game image
to fit the exact resolution of your LCD monitor.
With an HighDefinition monitor (1920x1080/1200), this stretching
is not noticeable and you get an image with quality comparable
with a CRT Multi\(hySync monitor.
You can also use a bunch of video effects to remove the
annoying pixelation or to emulate old stylish CRT aspect.
.SS With a CRT Multi\(hySync Monitor 
On a PC Multi\(hySync monitor you can get any resolution at any
Vertical Frequency. In this case AdvanceMAME always generates
a \(oqperfect\(cq video mode with the correct size and clock. It
doesn\(cqt require any type of stretching.
For example for the game \(a"Bomb Jack\(a" a video mode of 400x256
at 60 Hz (perfect size and perfect frequency) is used.
.SS With a CRT VGA Monitor/Fixed Frequency Monitor/Arcade Monitor 
On Fixed Frequency monitors you are physically limited on
the choice of Horizontal Frequency in the video mode. In this
case AdvanceMAME takes care of your monitor\(cqs limitations
and in the most cases it\(cqs able to use a video mode with the
correct size but not with the correct frequency due to the
monitor\(cqs limitations.
For example for the game \(a"Pac\(hyMan\(a" and a VGA monitor (31.5 kHz)
a video mode of 400x288 at 100 Hz (perfect size) is used.
.SS With a NTSC or PAL TV 
On a TV you are physically limited to use both fixed Horizontal
and Vertical Frequencies. This results on a prefixed number of
rows for the video mode.
For example for a NTSC TV you can get 240 rows (480 if
interlaced) and for a PAL TV 288 rows (576 if interlaced).
In this case AdvanceMAME uses a video mode with the prefixed
number of rows but with the correct number of columns. So,
ONLY a vertical image stretching is required.
For example for the game \(a"Pac\(hyMan\(a" on a NTSC TV a video mode
of 400x240 (perfect horizontal size) is used.
For stretching some special algorithms are used to minimize
the lose of details.
.SS With a Multi\(hyformat NTSC and PAL TV 
If your TV supports both formats, AdvanceMAME automatically
chooses the format that better fits the game requirements.
For example for the game \(a"Mr. Do!\(a" a video mode of 336x240
NTSC (perfect size) is used. For the game \(a"Pac\(hyMan\(a" a video mode
of 400x288 PAL (perfect size) is used.
.SH OTHER PORTS 
This section compares the AdvanceMAME video support with the
other MAME ports.
.SS Windows MAME 
The official Windows MAME is forced by Windows drivers to select
a video mode from a prefixed list of mode sizes and clocks.
If the emulated game requires a not standard mode size the
emulator must stretch the game image to fit the screen (losing in
quality). If the emulated games requires a not standard clock the
emulator must play the game without synchronizing with the video
vertical retrace (generating the tearing disturb on scrolling game)
or display frames for different time (generating a not constant
scrolling).
.PP
Depending on the type of your video drivers you can sometimes
edit the prefixed list of video modes.
.PP
The TV support depends on the video drivers of your board and
it\(cqs generally limited at the interlaced mode 640x480.
Arcade monitors are used as NTSC TVs.
.PP
Generally this port is limited by Windows to get the best from
your monitor.
.SS SDL MAME 
The official SDL MAME, is similar at AdvanceMAME when using the
sdl video driver, which is the default when run in a modern
Desktop environment.
.PP
AdvanceMAME has the benefit to allow to use more video effects,
able to improve the image quality.
.PP
This also helps when using Arcade Monitors with specific modelines,
because AdvanceMAME is able to streatch the image using special effects
like \(cqmax\(cq that avoids to lose pixels.
.SS DOS MAME 
The official DOS MAME is limited to use only the standard
VESA resolutions. Generally they are only 320x200,
320x240, 400x300, 512x384, 640x480, ...
.PP
The Arcade/TV support is limited at the mode 640x480 for the
ATI boards.
.SH CONFIGURATION 
In DOS and Windows the configuration options are read from the
files \(oqadvmame.rc\(cq and \(oqadvmess.rc\(cq in the current
directory.
.PP
In Linux and Mac OS X the configuration options are read from the
files \(oqadvmame.rc\(cq and \(oqadvmess.rc\(cq in the $host, $data and
the $home directory.
The $host directory is \(oq$SYSCONFDIR\(cq, where $SYSCONFDIR is the
\(oqsysconfdir\(cq directory configured with the \(oqconfigure\(cq script.
The default is \(oq/usr/local/etc\(cq.
The $data directory is \(oq$DATADIR/advance\(cq, where $DATADIR is the
\(oqdatadir\(cq directory configured with the \(oqconfigure\(cq script.
The default is \(oq/usr/local/share\(cq.
The $home directory is \(oq$ADVANCE\(cq, where $ADVANCE is the value of the
ADVANCE environment variable when the program is run.
If the ADVANCE environment variable is missing the $home directory
is \(oq$HOME/.advance\(cq where $HOME is the value of the HOME environment
variable.
If both the ADVANCE and HOME environment variables are missing the
$data directory became also the $home directory.
.PP
The priority of the options is in the order: $host, $home and $data.
.PP
The $home directory is also used to write all the information
by the program. The files in the $host and $data directory are only read.
.PP
You can include an additional configuration files with the \(oqinclude\(cq
option. In DOS and Windows the files are searched in the current directory.
In Linux and Mac OS X the files are searched in the $home directory if
they are expressed as a relative path. You can force the search in the
current directory prefixing the file with \(oq./\(cq.
To include more than one file you must divide the names with \(oq;\(cq in
DOS and Windows, and with \(oq:\(cq in Linux and Mac OS X.
.PP
You can force the creation of a default configuration file with the
command line option \(oq\(hydefault\(cq.
.PP
In the configuration file the options are specified in this format:
.PP
.RS 4
[SECTION/]OPTION VALUE
.PD 0
.PP
.PD
.RE
.PP
If the SECTION is omitted the \(oq\(cq (empty) section is assumed.
.PP
You can split long options in a multi\(hyline format ending the line
with the char \(oq\(rs\(cq:
.PP
.RS 4
[SECTION/]OPTION FIRST_LINE \(rs
.PD 0
.PP
.PD
	SECOND_LINE \(rs
.PD 0
.PP
.PD
	... \(rs
.PD 0
.PP
.PD
	LAST_LINE
.PD 0
.PP
.PD
.RE
.PP
When you run a game every option is read in different
sections in the following order:
.RS 4
.PD 0
.HP 4
.I \(oqSYSTEM[SOFTWARE]\(cq
The short system name and the loaded
software on the command line, like \(oqti99_4a[ti\(hyinva]\(cq,
\(oqa7800[digdug]\(cq and \(oqnes[commando]\(cq.
.HP 4
.I \(oqGAME\(cq
The short game (or system) name, like \(oqpacman\(cq,
\(oqti99_4a\(cq and \(oqnes\(cq.
.HP 4
.I \(oqPARENT\(cq
If present, the parent name of the game,
like \(oqpuckman\(cq.
.HP 4
.I \(oqBIOS\(cq
If present, the bios name of the game,
like \(oqneogeo\(cq.
.HP 4
.I \(oqRESOLUTIONxCLOCK\(cq
The resolution and the clock of the
game, like \(oq244x288x60\(cq for raster games or
\(oqvector\(cq for vector games. If the vertical clock
is a real value, it\(cqs rounded downwards to the
nearest integer.
.HP 4
.I \(oqRESOLUTION\(cq
The resolution of the game, like
\(oq244x288\(cq for raster games or \(oqvector\(cq for
vector games.
.HP 4
.I \(oqORIENTATION\(cq
The game orientation. One of \(oqvertical\(cq,
\(oqhorizontal\(cq.
.HP 4
.I \(oqCONTROLLER\(cq
The game input device. One of \(oqjoy4way\(cq,
\(oqjoy8way\(cq, \(oqdoublejoy4way\(cq, \(oqdoublejoy8way\(cq,
\(oqpaddle\(cq, \(oqdial\(cq, \(oqtrackball\(cq, \(oqstick\(cq, \(oqlightgun\(cq,
\(oqmouse\(cq.
.HP 4
.I \(oqNplayer\(cq
Number of players in the game. One of \(oq1player\(cq,
\(oq2player\(cq, \(oq3player\(cq, ...
.HP 4
.I \(oq\(cq
The default empty section.
.PD
.RE
.PP
For example for the game \(oqpacman\(cq the following sections are
read: \(oqpacman\(cq, \(oqpuckman\(cq, \(oq224x288x60\(cq, \(oq224x288\(cq, \(oqvertical\(cq,
\(oqjoy4way\(cq, \(oq2player\(cq and \(oq\(cq.
.PP
You can override any global options inserting new options in
any of the sections of the game.
.PP
For example:
.PP
.RS 4
display_scanlines no
.PD 0
.PP
.PD
pacman/display_scanlines yes
.PD 0
.PP
.PD
244x288x60/display_scanlines yes
.PD 0
.PP
.PD
vertical/display_ror yes
.PD 0
.PP
.PD
horizontal/display_ror no
.PD 0
.PP
.PD
.RE
.SS Software Configuration Options 
This section describes the options used to customize the
software loaded by system emulated.
.SS dev_* 
Loads a specific device for the AdvanceMESS emulator. These
options are mainly used on the command line to specify the
machine software to load.
The file specified is searched in the directory list specified
in the \(oqdir_image\(cq option.
.PP
dev_COMMAND FILE
.PD 0
.PP
.PD
.PP
Commands:
.RS 4
.PD 0
.HP 4
.I cartridge
Load a cartridge.
.HP 4
.I floppydisk
Load a floppydisk.
.HP 4
.I harddisk
Load an harddisk.
.HP 4
.I cylinder
Load a cylinder.
.HP 4
.I cassette
Load a cassette.
.HP 4
.I punchcard
Load a punchcard.
.HP 4
.I punchtape
Load a punchtape.
.HP 4
.I printer
Load a printer.
.HP 4
.I serial
Load a serial.
.HP 4
.I parallel
Load a parallel.
.HP 4
.I snapshot
Load a snapshot.
.HP 4
.I quickload
Load a quickload.
.PD
.RE
.PP
Examples:
.PP
.RS 4
advmess ti99_4a \(hydev_cartridge attackg.bin
.PD 0
.PP
.PD
advmess ti99_4a \(hycart alpinerc.bin \(hycart alpinerg.bin
.PD 0
.PP
.PD
.RE
.SS Directory Configuration Options 
This section describes the options used to customize the
directories used by the program.
.SS dir_* 
Specify all the support directories. In DOS and Windows use the \(oq;\(cq
char as directory separator. In Linux and Mac OS X use the \(oq:\(cq char.
.PP
dir_* DIR[;DIR]... (DOS, Windows)
.PD 0
.PP
.PD
dir_* DIR[:DIR]... (Linux, Mac OS X)
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I dir_rom
Multi directory specification for the
AdvanceMAME \(oqrom\(cq files and AdvanceMESS \(oqbios\(cq
files.
.HP 4
.I dir_image
Multi directory specification for the
chd/disk/cartdrige/... image files.
.HP 4
.I dir_diff
Multi directory specification for the
disk image differential files.
.HP 4
.I dir_sample
Multi directory specification for the
zipped \(oqsample\(cq files. Only the zipped format
is supported.
.HP 4
.I dir_artwork
Multi directory specification for the
zipped \(oqartwork\(cq files. Only the zipped format
is supported.
.HP 4
.I dir_nvram
Single directory for \(oqnvram\(cq files.
.HP 4
.I dir_memcard
Single directory for \(oqmemcard\(cq files.
.HP 4
.I dir_hi
Single directory for \(oqhi\(cq files.
.HP 4
.I dir_inp
Single directory for \(oqinp\(cq files.
.HP 4
.I dir_sta
Single directory for \(oqsta\(cq files.
.HP 4
.I dir_snap
Single directory for the \(oqsnapshot\(cq
files.
.HP 4
.I dir_crc
Single directory for the \(oqcrc\(cq files.
.PD
.RE
.PP
Defaults for DOS and Windows:
.RS 4
.PD 0
.HP 4
.I dir_rom
rom
.HP 4
.I dir_image
image
.HP 4
.I dir_diff
diff
.HP 4
.I dir_sample
sample
.HP 4
.I dir_artwork
artwork
.HP 4
.I dir_nvram
nvram
.HP 4
.I dir_memcard
memcard
.HP 4
.I dir_hi
hi
.HP 4
.I dir_inp
inp
.HP 4
.I dir_sta
sta
.HP 4
.I dir_snap
snap
.HP 4
.I dir_crc
crc
.PD
.RE
.PP
Defaults for Linux and Mac OS X:
.RS 4
.PD 0
.HP 4
.I dir_rom
$home/rom:$data/rom
.HP 4
.I dir_image
$home/image:$data/image
.HP 4
.I dir_diff
$home/image:$data/diff
.HP 4
.I dir_sample
$home/sample:$data/sample
.HP 4
.I dir_artwork
$home/artwork:$data/artwork
.HP 4
.I dir_nvram
$home/nvram
.HP 4
.I dir_memcard
$home/memcard
.HP 4
.I dir_hi
$home/hi
.HP 4
.I dir_inp
$home/inp
.HP 4
.I dir_sta
$home/sta
.HP 4
.I dir_snap
$home/snap
.HP 4
.I dir_crc
$home/crc
.PD
.RE
.PP
If a not absolute dir is specified, in Linux and Mac OS X
it\(cqs expanded as \(a"$home/DIR:$data/DIR\(a". In DOS and Windows
it\(cqs maintained relative.
.PP
For the \(oqdir_rom\(cq and \(oqdir_image\(cq the following file
combinations are tried:
.PD 0
.IP \(bu
DIR/GAME/ROM.EXT
.IP \(bu
DIR/GAME.zip/ROM.EXT
.IP \(bu
DIR/GAME/ROM.zip/ROM
.PD
.PP
Where DIR is substituted with the directories specified, GAME
is the name of the game or machine emulated, ROM is the rom
name and EXT is the rom extension.
.PP
For the files searched in the \(oqdir_image\(cq option you can also
specify a different zip name prefixing the rom name
with the zip name without extension and the \(oq=\(cq char.
For example to run the \(oqti99_4a\(cq emulator and load the
cartdriges \(oqalpinerc.bin\(cq and \(oqalpinerg.bin\(cq both contained in
the zip file \(oqalpiner.zip\(cq you can use this syntax:
.PP
.RS 4
advmess ti99_4a \(hycart alpiner=alpinerc.bin \(hycart alpiner=alpinerg.bin
.PD 0
.PP
.PD
.RE
.PP
This feature is used automatically by AdvanceMENU to correctly
run AdvanceMESS software in zip files.
.SS Display Configuration Options 
This section describes the options used to customize the
display.
.SS device_video_* 
These options are used to customize the video drivers.
.PP
All the \(oqdevice_video_*\(cq options described in the \(oqadvdev.txt\(cq file
can be used.
.PP
If you use a \(oqSystem\(cq video driver, you don\(cqt need to set these
options. They are mostly ignored.
.PP
With a \(oqGenerate\(cq video drivers these options are used to select
and create the correct video mode. They are mandatory. You can use
the \(oqadvcfg\(cq utility to set them interactively.
.SS display_mode 
Selects a specific modeline by its name.
.PP
display_mode auto | MODELINE_NAME
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I MODELINE_NAME
Specific modeline, as named with
the \(oqadvv\(cq utility.
.HP 4
.I auto
Automatically chooses the best modeline
available (default).
.PD
.RE
.SS display_adjust 
Controls how are generate the video modes. Correct use of this
option removes the need of any software stretching improving a
lot the game image.
.PP
For an introduction on how the program operates on video mode,
you can see the \(oqinstall.txt\(cq file.
.PP
display_adjust none | x | clock | xclock | generate_exact
.PD 0
.PP
.PD
	| generate_y | generate_clock | generate_clocky
.PD 0
.PP
.PD
	| generate_yclock
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I none
No automatic video mode creation. Use only the
available modelines (default).
.HP 4
.I x
Adjusts the available modeline horizontal resolution
to match the game image\(cqs size. The stretched modeline
keeps all the clock attributes of the original
modeline. Also all other modeline attributes,
like doublescan and interlace, are maintained.
.HP 4
.I clock
Adjusts the available modeline\(cqs vertical clock
to match the game\(cqs frame rate.
.HP 4
.I xclock
Adjusts the available modeline\(cqs horizontal resolution
and the vertical clock.
.HP 4
.I generate_exact
Creates automatically some new modelines using
the format specified on the \(oqdevice_video_format\(cq
option. The generated modelines will be named \(oqgenerate\(hy*\(cq.
Check the \(oqadvdef.txt\(cq file for the description of
the \(oqdevice_video_format\(cq option or simply use the
\(oqadvcfg\(cq utility to set it up correctly.
If the \(oqdevice_video_format\(cq option isn\(cqt
specified a default value for your monitor clock
limits is guessed.
.HP 4
.I generate_y
Like generate_exact, and it allows generating
modes with a wrong vertical size if a perfect mode is not
possible.
.HP 4
.I generate_clock
Like generate_exact, and it allows generating
modes with a vertical clock different than the game
original clock if a perfect mode is not	possible.
.HP 4
.I generate_yclock
Like generate_exact, and it allows
generating modes with a wrong vertical clock and/or size
if a perfect mode is not possible. Modes with a correct size
are favorite over mode than a correct clock.
.HP 4
.I generate_clocky
Like generate_exact, and it allows
generating modes with a wrong vertical clock and/or size
if a perfect mode is not possible. Modes with a correct clock
are favorite over mode with a correct size.
.PD
.RE
.PP
The \(oqgenerate\(cq options are able to create at runtime all the
required modelines. You don\(cqt need to create a list of modelines
manually.
.PP
The not \(oqgenerate\(cq options use only the modelines defined with
the \(oqdevice_video_modeline\(cq option in the configuration file.
You can add them manually or using the \(oqadvv\(cq utility.
Check the \(oqadvdev.txt\(cq file for more details on the
\(oqdevice_video_modeline\(cq option.
.PP
Of all the \(oqgenerate\(cq options, the \(oqgenerate_yclock\(cq is the
suggested and the most powerful. The \(oqadvcfg\(cq utility always
sets the \(oqgenerate_yclock\(cq option in your configuration file.
.PP
Of all the not \(oqgenerate\(cq options, the \(oqxclock\(cq is the
suggested and the most powerful.
.PP
If you can\(cqt get good result with the \(oqgenerate\(cq options you
should create a list of modelines and try with the \(oqxclock\(cq value.
You don\(cqt need to duplicate the same modeline with different
horizontal resolutions and/or the clocks, because the \(oqxclock\(cq
value allows the program to adjust them.
Instead, you should create a wide set of different vertical
resolutions on which the video mode can be chosen.
A good choice is to create all the resolutions with a step of
16 rows.
.SS display_color 
Controls the color format of the video mode.
.PP
display_color auto | palette8 | bgr8 | bgr15 | bgr16 | bgr32 | yuy2
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I auto
Automatically choose the best option (default).
.HP 4
.I palette8
Palettized 8 bits mode.
.HP 4
.I bgr8
RGB 8 bits mode.
.HP 4
.I bgr15
RGB 15 bits mode.
.HP 4
.I bgr16
RGB 16 bits mode.
.HP 4
.I bgr32
RGB 32 bits mode.
.HP 4
.I yuy2
YUV mode in the YUY2 format.
.PD
.RE
.PP
Note that the 24 bit color mode isn\(cqt supported.
.PP
The modes are called bgr because in the video memory the order of
the color channel is: Blue, Green, Red.
.SS display_resize 
Suggests the favorite image stretching when a video mode
with the correct size isn\(cqt available.
This option doesn\(cqt have any effect for vector games, they are
always stretched to fit the whole screen.
.PP
display_resize none | integer | mixed | fractional
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I none
Original size.
.HP 4
.I integer
Integer stretch, i.e. x2, x3, x4,...
.HP 4
.I mixed
Integer horizontal stretch and fractional
vertical stretch.
.HP 4
.I fractional
Fractional stretch (default).
.PD
.RE
.PP
The \(oqfractional\(cq option involves a slowdown, so use the \(oqmixed\(cq
option if you have a really slow machine.
.PP
Examples:
.PP
.RS 4
display_resize mixed
.PD 0
.PP
.PD
.RE
.SS display_magnify 
Suggests the use of a double or bigger resolution video mode.
It is mainly used to enable the \(oqscalex\(cq, \(oqscalek\(cq, \(oqlq\(cq, \(oqhq\(cq and \(oqxbr\(cq
effects. This option doesn\(cqt have any effect for vector games.
.PP
display_magnify auto | 1 | 2 | 3 | 4
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I auto
Double, triplicate or quadruplicate the size until
targetting the defined display_magnifysize
horizontal size (default).
.HP 4
.I 1
Normal size.
.HP 4
.I 2
Double size.
.HP 4
.I 3
Triple size.
.HP 4
.I 4
Quadruple size.
.PD
.RE
.SS display_magnifysize 
Defines the target area to reach with the auto config of display_magnify.
The specified value is the edge of the square area to target.
For example, with 512 the game area is expanded up to reach the size
of 512*512 pixels.
.PP
display_magnifysize SIZE
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I SIZE
Square root of the area to target. Default 600.
The default of 600 typicall uses a magnify
factor of 2.
.PD
.RE
.SS display_scanlines 
Suggests the use of hardware scanlines when choosing
the video mode.
.PP
display_scanlines yes | no
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I yes
Try to select a singlescan video mode.
.HP 4
.I no
Try to select a doublescan video mode (default).
.PD
.RE
.SS display_buffer 
Activates the video image buffering.
.PP
display_buffer yes | no
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I no
Doesn\(cqt use any buffering (default).
.HP 4
.I yes
Use the best buffering available.
.PD
.RE
.SS display_vsync 
Synchronizes the video display with the video beam instead of
using the CPU timer. This option can be used only if the
selected video mode has an appropriate refresh rate.
To ensure this you can use the option \(oqdisplay_adjust\(cq to allow
a clock correction of the video mode.
.PP
display_vsync yes | no
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I no
Use the timer.
.HP 4
.I yes
Use the video refresh rate (default).
.PD
.RE
.PP
You can enable or disable it also on the runtime Video menu.
.SS display_restore 
Selects whether or not to reset to default text mode at the
emulator exit.
.PP
display_restore yes | no
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I yes
Resets to text mode (default).
.HP 4
.I no
Doesn\(cqt change the video mode.
.PD
.RE
.SS display_frameskip 
Skips frames to speed up the emulation.
.PP
display_frameskip auto | FACTOR
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I auto
Auto frame skip (default).
.HP 4
.I FACTOR
Float factor for the fraction of frames
to display. From 0 to 1. To completely
disable the frame skipping use the
value 1.
.PD
.RE
.PP
Use \(oqf11\(cq to display the speed your computer is actually
reaching. If it is below 100%, increase the frame skip value.
You can press \(oqf8/f9\(cq to change frame skip while running the game.
When set to auto (default), the frame skip setting is
dynamically adjusted during runtime to display the maximum
possible frames without dropping below the 100% speed.
Pressing \(oqf10\(cq you can enable and disable the throttle
synchronization.
.PP
Examples:
.PP
.RS 4
display_frameskip 0.5
.PD 0
.PP
.PD
.RE
.SS Display Aspect Configuration Options 
This section describes the options used to customize the display
aspect.
.SS display_expand 
Enlarges the screen area used by the vertical games on horizontal
monitors (and horizontal games in vertical monitors).
.PP
display_expand FACTOR
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I FACTOR
Expansion float factor from 1.0 to 2.0
(default 1.0).
.PD
.RE
.PP
Examples:
.PP
.RS 4
display_expand 1.15
.PD 0
.PP
.PD
.RE
.SS display_aspectx/aspecty 
Selects the aspect of the monitor used.
.PP
display_aspectx INT
.PD 0
.PP
.PD
display_aspecty INT
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I INT
Integer number starting from 1 (default 4 and 3).
.PD
.RE
.PP
For 16/9 TV you can use the 16 and 9 values. For truly vertical
monitors (not horizontal monitors rotated) you can simply swap the
values, for example 3 and 4 instead of 4 and 3.
.PP
Examples:
.PP
.RS 4
display_aspectx 16
.PD 0
.PP
.PD
display_aspecty 9
.PD 0
.PP
.PD
.RE
.SS display_ror/rol/flipx/flipy 
Flips and rotates the game image.
.PP
display_ror yes | no
.PD 0
.PP
.PD
display_rol yes | no
.PD 0
.PP
.PD
display_flipx yes | no
.PD 0
.PP
.PD
display_flipy yes | no
.PD 0
.PP
.PD
.PP
Examples:
.PP
.RS 4
To rotate left vertical games:
.RE
.PP
.RS 4
vertical/display_rol yes
.PD 0
.PP
.PD
.RE
.SS display_skiplines/skipcolumns 
Selects the centering of the visible area.
.PP
display_skiplines auto | SKIPLINES
.PD 0
.PP
.PD
display_skipcolumns auto | SKIPCOLUMNS
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I auto
Auto center (default).
.HP 4
.I SKIPLINES
Lines to skip.
.HP 4
.I SKIPCOLUMNS
Columns to skip.
.PD
.RE
.SS Display Effect Configuration Options 
This section describes the options used to customize the display
effects.
.SS display_resizeeffect 
When a video mode is smaller or bigger than the original arcade
screen, the \(oqresizeeffect\(cq option controls the type of the
transformation applied.
.PP
display_resizeeffect auto | none | max | mean | filter
.PD 0
.PP
.PD
	| scalex | scalek | lq | hq | xbr
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I auto
Selects automatically the best effect (default).
This selection is list based, and may be
incomplete.
If the scale factor is 2, 3 o 4 the \(oqxbr\(cq effect
is selected. The effect is automatically downgraded
to \(oqscalek\(cq or \(oqscalex\(cq if the emulation is too slow.
On the other cases the \(oqmean\(cq or \(oqmax\(cq effect
is selected.
.HP 4
.I none
Simply removes or duplicates lines as required.
.HP 4
.I max
In reduction merges consecutive columns and rows using the
lightest pixels versus the darkest.
In expansion duplicate columns and rows using the
darkest pixels versus the lightest.
Supported in both rgb and palette video modes.
It works best for the games with black
background or without scrolling. Like \(a"Pac\(hyMan\(a".
This effect ensures to have always rows and columns
of the same thickness.
.HP 4
.I mean
In reduction it merges columns and rows using the
mean color of the pixels. In expansion it adds
columns and rows that are the mean of previous
and next lines.
Supported only in rgb video modes.
It works best for the games with animated
or scrolling background. Like \(a"1941\(a".
.HP 4
.I filter
It removes or duplicates columns and rows with
a low pass filter in the x and the y directions.
It\(cqs a simple FIR filter with two points of
equal value.
Supported only in rgb video modes.
.HP 4
.I scalex
It adds the missing pixels matching the
original bitmap pattern.
It uses a 3x3 mapping analysis with 4 comparisons.
It doesn\(cqt interpolate pixels and it compares colors
for equality.
If works only for expansion factor of 2, 3 and 4.
.HP 4
.I scalek
It adds the missing pixels matching the
original bitmap pattern.
It uses a 3x3 mapping analysis with 4 comparisons.
It interpolates pixels and it compares colors
for equality.
If works only for expansion factor of 2, 3 and 4.
.HP 4
.I lq
It adds the missing pixels matching the
original bitmap pattern.
It uses a 3x3 mapping analysis with 8 comparisons.
It interpolates pixels and it compares colors for equality.
It works only for expansion factor of 2, 3 and 4.
.HP 4
.I hq
It adds the missing pixels matching the
original bitmap pattern.
It uses a 3x3 mapping analysis with 8 comparisons.
It interpolates pixels and it compares colors
for distance.
It works only for expansion factor of 2, 3 and 4.
.HP 4
.I xbr
It adds the missing pixels matching the
original bitmap pattern.
It uses a 5x5 mapping analysis with a gradient estimation.
It interpolates pixels and it compares colors
for distance.
It works only for expansion factor of 2, 3 and 4.
.PD
.RE
.SS display_rgbeffect 
Selects a special effect to simulate the aspect of an Arcade Monitor
with a PC monitor. The resulting image is better when you use a
big video mode. These effects require a RGB video mode, they don\(cqt
work with palettized or YUV modes.
.PP
display_rgbeffect none | triad3dot | triad6dot
.PD 0
.PP
.PD
	| triad16dot | triadstrong3dot | triadstrong6dot
.PD 0
.PP
.PD
	| triadstrong16dot | scan2vert | scan3vert
.PD 0
.PP
.PD
	| scan2horz | scan3horz.
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I none
No effect (default).
.HP 4
.I triad3dot
RGB triad of 3 pixels.
.HP 4
.I triad6dot
RGB triad of 6 pixels.
.HP 4
.I triad16dot
RGB triad of 16 pixels.
.HP 4
.I triadstrong3dot
RGB strong triad of 3 pixels.
.HP 4
.I triadstrong6dot
RGB strong triad of 6 pixels.
.HP 4
.I triadstrong16dot
RGB strong triad of 16 pixels.
.HP 4
.I scan2vert
Scanline of 2 vertical lines.
.HP 4
.I scan3vert
Scanline of 3 vertical lines.
.HP 4
.I scan2horz
Scanline of 2 horizontal lines.
.HP 4
.I scan3horz
Scanline of 3 horizontal lines.
.PD
.RE
.SS display_interlaceeffect 
Selects some special effects for interlaced video modes.
On not interlaced modes the effects are always disabled.
.PP
display_interlaceeffect none | even | odd | filter
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I none
No effect (default).
.HP 4
.I even
Swap the even rows.
.HP 4
.I odd
Swap the odd rows.
.HP 4
.I filter
Apply a vertical filter.
.PD
.RE
.PP
If your monitor uses a swapped order for interlaced rows, using the
\(oqeven\(cq or \(oqodd\(cq effect you can probably fix the image.
.PP
The effects operate on the rows in the following way:
.PP
.RS 4
Row Even Odd Filter
.PD 0
.PP
.PD
 A   A   A    A
.PD 0
.PP
.PD
 B   B   A   B+A
.PD 0
.PP
.PD
 C   A   C   C+B
.PD 0
.PP
.PD
 D   D   B   D+C
.PD 0
.PP
.PD
 E   C   E   E+D
.PD 0
.PP
.PD
 F   F   D   F+E
.PD 0
.PP
.PD
 G   E   G   G+F
.PD 0
.PP
.PD
 H   H   F   H+G
.PD 0
.PP
.PD
.RE
.SS Display Color Configuration Options 
This section describes the options used to customize the display
color adjustments.
.SS display_brightness 
Selects the image brightness factor.
.PP
display_brightness FACTOR
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I FACTOR
Brightness float factor (default 1.0).
.PD
.RE
.SS display_gamma 
Sets the image gamma correction factor.
.PP
display_gamma FACTOR
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I FACTOR
Gamma float factor (default 1.0).
.PD
.RE
.SS display_pausebrightness 
Selects the brightness of the display when game is paused.
.PP
display_pausebrightness FACTOR
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I FACTOR
Float brightness factor.
From 0.0 to 1.0 (default 1.0).
.PD
.RE
.PP
Examples:
.PP
.RS 4
display_pausebrightness 0.6
.PD 0
.PP
.PD
.RE
.SS Display Artwork Configuration Options 
This section describes the options used to customize the display
artwork.
.SS display_artwork_backdrop/overlay/bezel 
Enables or disables the artworks display.
.PP
display_artwork_backdrop yes | no
.PD 0
.PP
.PD
display_artwork_overlay yes | no
.PD 0
.PP
.PD
display_artwork_bezel yes | no
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I yes
Enables the artwork (default for backdrop
and overlay).
.HP 4
.I no
Doesn\(cqt display the artwork (default for
bezel).
.PD
.RE
.SS display_artwork_crop 
Crops the artwork at the game size.
.PP
display_artwork_crop yes | no
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I yes
Crops the artwork (default).
.HP 4
.I no
Doesn\(cqt crop the artwork.
.PD
.RE
.SS Display Vector Configuration Options 
This section describes the options used to customize the display
of vector games.
.SS display_antialias 
Enables or disables the anti\(hyaliasing for vector games.
.PP
display_antialias yes | no
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I yes
Anti\(hyaliasing enabled (default)
.HP 4
.I no
Anti\(hyaliasing disabled.
.PD
.RE
.SS display_beam 
Sets width in pixels of vectors.
.PP
display_beam SIZE
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I SIZE
A float in the range of 1.0 through 16.0
(default 1.0).
.PD
.RE
.SS display_flicker 
Makes vectors flicker.
.PP
display_flicker FACTOR
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I FACTOR
A float in the range 0.0 \(hy 100.0
(default 0).
.PD
.RE
.SS display_translucency 
Enables or disables vector translucency.
.PP
display_translucency yes | no
.PD 0
.PP
.PD
.SS display_intensity 
Sets the vector intensity.
.PP
display_intensity FACTOR
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I FACTOR
A float in the range 0.5 \(hy 3.0
(default 1.5).
.PD
.RE
.SS Sound Configuration Options 
This section describes the options used to customize the sound.
.SS device_sound_* 
These options are used to customize the audio drivers.
.PP
All the \(oqdevice_sound_*\(cq options defined in the \(oqadvdev.txt\(cq
file can be used.
.SS sound_mode 
Sets the sound output mode.
.PP
sound_mode auto | mono | stereo | surround
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I auto
Use mono if the emulated game is mono
or stereo if it\(cqs stereo (default).
.HP 4
.I mono
Use always mono. The game stereo channels
are mixed.
.HP 4
.I stereo
Use always stereo. The game mono channel
is duplicated.
.HP 4
.I surround
Use a fake surround effect. With
stereo games the right channel plays part of
the left channel as negate samples and vice\(hyversa.
With mono games the left channel is the negation of
the right channel. This means that with surround
enabled the output is always stereo.
If you use mono headphones, the effect will not
work and you will hear silence or an attenuated
sound.
.PD
.RE
.SS sound_samplerate 
Sets the audio sample rate.
.PP
sound_samplerate RATE
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I RATE
Sample rate. Common values are 11025, 22050,
44100 and 48000 (default 44100).
.PD
.RE
.PP
If the sound driver doesn\(cqt support the specified sample rate a
different value is selected.
.SS sound_volume 
Sets the global sound volume.
.PP
sound_volume VOLUME
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I VOLUME
The volume attenuation in dB (default \(hy3).
The attenuation is a negative value from \(hy40 to 0.
.PD
.RE
.PP
Examples:
.PP
.RS 4
sound_volume \(hy5
.PD 0
.PP
.PD
.RE
.SS sound_adjust 
Sets the sound gain volume. This option can be used to
adjust the volume of some games to have all the games with
the same volume.
If the \(oqsound_normalize\(cq option is active this value is
also automatically updated in the game play and you cannot
change it manually.
.PP
sound_adjust auto | VOLUME
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I auto
Get the value for the current game from
an internal database.
.HP 4
.I VOLUME
The volume gain in dB (default 0).
The gain is a positive value from 0 to 40.
If the \(oqsound_normalize\(cq option is active the
volume is automatically updated in the game
play.
.PD
.RE
.PP
Examples:
.PP
.RS 4
sound_adjust 16
.PD 0
.PP
.PD
.RE
.SS sound_normalize 
Automatically increases and decreases the sound volume.
.PP
sound_normalize yes | no
.PD 0
.PP
.PD
.PP
Precisely, the program continously measures the normalized
sound power adjusting it with the Fletcher\(hyMunson \(a"Equal
Loudness Courve\(a" at 80 dB to remove inaudible frequencies.
It tries to keep constant the 95% median power of the
last 3 minutes.
.PP
For more details check:
.PP
.RS 4
http://replaygain.hydrogenaudio.org/equal_loudness.html
.PD 0
.PP
.PD
.RE
.PP
Options:
.RS 4
.PD 0
.HP 4
.I yes
Enable the volume normalization (default).
.HP 4
.I no
Disable it.
.PD
.RE
.SS sound_equalizer_* 
Sets the equalizer volume. To disable the equalizer set
all the VOLUME values to 0. The cut\(hyoff frequencies are 800
and 8000 Hz.
.PP
sound_equalizer_lowvolume VOLUME
sound_equalizer_midvolume VOLUME
sound_equalizer_highvolume VOLUME
.PP
Options:
.RS 4
.PD 0
.HP 4
.I VOLUME
The volume gain in dB (default 0).
The gain is a integer value from \(hy20 to 20.
.PD
.RE
.SS sound_latency 
Sets the minimum audio latency.
.PP
sound_latency TIME
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I TIME
Latency in seconds from 0 to 2.0
(default 0.05).
.PD
.RE
.PP
If in the game play you hear some sound ticks you can try to
increase the latency. Try doubling the value until the ticks
go away.
.SS Input Configuration Options 
This section describes the options used to customize the user
input.
.SS device_keyboard/joystick/mouse_* 
These options are used to customize the input drivers.
.PP
All the \(oqdevice_keyboard/joystick/mouse_*\(cq options defined in
the \(oqadvdev.txt\(cq file can be used.
.SS input_steadykey 
Helps recognition of very long key sequences. But slows a bit
the key recognition.
.PP
input_steadykey yes | no
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I no
Standard key recognition (default).
.HP 4
.I yes
Wait until the keyboard state is stabilized
before report any key change.
.PD
.RE
.SS input_hotkey 
Enables or disables the recognition of the special OS keyboard
sequences.
.PP
input_hotkey yes | no
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I no
No hot key recognition.
.HP 4
.I yes
Hot key recognition (default).
.PD
.RE
.PP
In DOS the hotkey recognized are:
.RS 4
.PD 0
.HP 4
.I CTRL+ALT+DEL
Reset.
.HP 4
.I CTRL+ALT+END
Quit.
.HP 4
.I CTRL+BREAK (Pause)
Break.
.PD
.RE
.PP
In Linux the hotkey recognized generally are:
.RS 4
.PD 0
.HP 4
.I CTRL+C
Break.
.HP 4
.I ALT+Fx
Change virtual console.
.PD
.RE
.SS input_idleexit 
Activates the automatic exit after some time of inactivity.
.PP
input_idleexit TIME
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I TIME
Number of seconds to wait, if 0 (default)
never exits automatically.
.PD
.RE
.SS input_map[ANALOG] 
Changes the analog control mapping. Maps joystick, trackball
and mouse controls on a player analog control.
.PP
input_map[ANALOG] auto | [[\(hy]joystick[JOY,CONTROL,AXE]]
.PD 0
.PP
.PD
	[[\(hy]mouse[MOUSE,AXE]] [[\(hy]joystick_ball[JOY,AXE]] ...
.PD 0
.PP
.PD
.PP
The default is always \(oqauto\(cq.
.PP
Options:
.RS 4
.PD 0
.HP 4
.I ANALOG
Player analog control. One of:
p1_paddlex, p2_paddlex, p3_paddlex, p4_paddlex,
p1_paddley, p2_paddley, p3_paddley, p4_paddley,
p1_stickx, p2_stickx, p3_stickx, p4_stickx,
p1_sticky, p2_sticky, p3_sticky, p4_sticky,
p1_stickz, p2_stickz, p3_stickz, p4_stickz,
p1_lightgunx, p2_lightgunx, p3_lightgunx, p4_lightgunx,
p1_lightguny, p2_lightguny, p3_lightguny, p4_lightguny,
p1_pedalgas, p2_pedalgas, p3_pedalgas, p4_pedalgas,
p1_pedalbrake, p2_pedalbrake, p3_pedalbrake, p4_pedalbrake,
p1_pedalother, p2_pedalother, p3_pedalother, p4_pedalother,
p1_dialx, p2_dialx, p3_dialx, p4_dialx,
p1_dialy, p2_dialy, p3_dialy, p4_dialy,
p1_trackballx, p2_trackballx, p3_trackballx, p4_trackballx,
p1_trackbally, p2_trackbally, p3_trackbally, p4_trackbally,
p1_mousex, p2_mousex, p3_mousex, p4_mousex,
p1_mousey, p2_mousey, p3_mousey, p4_mousey.
.HP 4
.I \(hy
Invert the direction of the movement.
.HP 4
.I JOY
Number of physical joystick: 0, 1, 2, 3, ...
.HP 4
.I MOUSE
Number of physical mouse: 0, 1, 2, 3, ...
.HP 4
.I CONTROL
Number or name of physical control of the joystick: 0, 1, 2, 3, ...
.HP 4
.I AXE
Number or name of physical axe of the
control: 0, 1, 2, 3 ...
.PD
.RE
.PP
The \(oqjoystick\(cq option is used to reference all the analog
controls which report an absolute position. For example
stick, lightgun, steering wheel, pedal, throttle and rudder controls.
.PP
The \(oqjoystick_ball\(cq and \(oqmouse\(cq options are used to reference
all the analog controls which reports a relative position. For
example trackball, dial and mouse controls.
The option \(oqjoystick_ball\(cq is for joystick devices which
have other relative analog controls. The option \(oqmouse\(cq is
for mouse devices which have only relative analog controls.
.PP
The exact CONTROL and AXE names can be checked interactively
using the \(oqadvj\(cq and \(oqadvm\(cq utility. \(oqadvj\(cq is used for
\(oqjoystick[]\(cq and \(oqjoystick_ball[]\(cq specifications. \(oqadvm\(cq is
used for \(oqmouse[]\(cq specifications.
.PP
The CONTROL names for the \(oqjoystick\(cq option are:
.RS 4
.PD 0
.HP 4
.I stick
Stick.
.HP 4
.I gas
Acceleration pedal.
.HP 4
.I brake
Brake pedal.
.HP 4
.I wheel
Steering wheel.
.HP 4
.I hat, hat2, hat3, hat4
Hats.
.HP 4
.I throttle
Throttle.
.HP 4
.I rudder
Rudder.
.HP 4
.I misc
Any other.
.PD
.RE
.PP
The AXE names for the \(oqjoystick\(cq option are:
.RS 4
.PD 0
.HP 4
.I x, y, z
Movement on the X, Y, Z axe.
.HP 4
.I rx, ry, rz
Rotation on the X, Y, Z axe.
.HP 4
.I mono
For all the control with a single axe.
.PD
.RE
.PP
The AXE names for the \(oqjoystick_ball\(cq and \(oqmouse\(cq
options are:
.RS 4
.PD 0
.HP 4
.I x, y, z
Movement on the X, Y, Z axe.
.HP 4
.I wheel
Vertical wheel.
.HP 4
.I hwheel
Horizontal wheel.
.HP 4
.I dial
Dial.
.HP 4
.I misc
Any other.
.PD
.RE
.PP
The ANALOG controls are always formed with a \(a"player\(a" string
and with a \(a"control\(a" strings.
.RS 4
.PD 0
.HP 4
.I p1_CONTROL
Player 1.
.HP 4
.I p2_CONTROL
Player 2.
.HP 4
.I p3_CONTROL
Player 3.
.HP 4
.I p4_CONTROL
Player 4.
.HP 4
.I PLAYER_paddlex
Paddle in horizontal direction.
.HP 4
.I PLAYER_paddley
Paddle in vertical direction.
.HP 4
.I PLAYER_stickx
Stick in horizontal direction.
.HP 4
.I PLAYER_sticky
Stick in vertical direction.
.HP 4
.I PLAYER_stick_z
Stick in z axis direction.
.HP 4
.I PLAYER_lightgunx
Lightgun in horizontal direction.
.HP 4
.I PLAYER_lightguny
Lightgun in vertical direction.
.HP 4
.I PLAYER_pedalgas
Gas pedal.
.HP 4
.I PLAYER_pedalbrake
Brake pedal.
.HP 4
.I PLAYER_pedalother
Other pedal.
.HP 4
.I PLAYER_dialx
Dial in horizontal direction.
.HP 4
.I PLAYER_dialy
Dial in vertical direction.
.HP 4
.I PLAYER_trackballx
Trackball in horizontal direction.
.HP 4
.I PLAYER_trackbally
Trackball in vertical direction.
.HP 4
.I PLAYER_mousex
Mouse in horizontal direction.
.HP 4
.I PLAYER_mousey
Mouse in vertical direction.
.PD
.RE
.PP
Examples:
.PP
.RS 4
input_map[p1_stickx] joystick[0,0,x] \(hyjoystick[0,1,x]
.PD 0
.PP
.PD
input_map[p1_sticky] joystick[0,0,y] \(hyjoystick[0,1,y]
.PD 0
.PP
.PD
input_map[p1_trackballx] mouse[0,x] \(hymouse[1,x]
.PD 0
.PP
.PD
input_map[p1_trackbally] mouse[0,y] \(hymouse[1,y]
.PD 0
.PP
.PD
.RE
.PP
If required you can compose the options to get a rotation
of 45° of the control. For example:
.PP
.RS 4
input_map[p1_stickx] mouse[0,x] mouse[0,y]
.PD 0
.PP
.PD
input_map[p1_sticky] mouse[0,x] \(hymouse[0,y]
.PD 0
.PP
.PD
.RE
.SS input_map[DIGITAL] 
Changes the digital control mapping. Maps a sequence of
keyboard/mouse/joystick keys on a player button or analog
simulation digital control.
.PP
input_map[DIGITAL] auto | keyboard[KEYBOARD,KEY]
.PD 0
.PP
.PD
	| mouse_button[MOUSE,MOUSE_BUTTON] | joystick_button[JOY,JOY_BUTTON]
.PD 0
.PP
.PD
	| joystick_digital[JOY,CONTROL,AXE,DIR]
.PD 0
.PP
.PD
	| or | not | ...
.PD 0
.PP
.PD
.PP
The default is always \(oqauto\(cq which uses the standard mapping.
The previous mapping is always overwritten.
.PP
Options:
.RS 4
.PD 0
.HP 4
.I DIGITAL
Player button, analog simulation, digital or
keyboard control.
.HP 4
.I KEYBOARD
Number of physical keyboard: 0, 1, 2, 3, ...
.HP 4
.I KEY
Name of physical key.
.HP 4
.I MOUSE
Number of physical mouse: 0, 1, 2, 3, ...
.HP 4
.I MOUSE_BUTTON
Number or name of a physical mouse button:
0, 1, 2, 3, ...
.HP 4
.I JOY
Number of physical joystick: 0, 1, 2, 3, ...
.HP 4
.I CONTROL
Number or name of physical control of the joystick: 0, 1, 2, 3, ...
.HP 4
.I DIR
Direction of the movement: left, up, right, down.
.HP 4
.I AXE
Number or name of physical axe of the control: 0, 1, 2, 3, ...
.HP 4
.I JOY_BUTTON
Number or name of a physical joystick button:
0, 1, 2, 3, ...
.HP 4
.I or
Or operand.
.HP 4
.I not
Not operand.
.HP 4
.I auto
Use the default mapping.
.PD
.RE
.PP
The DIGITAL controls are:
.PP
.RS 4
p1_up, p2_up, p3_up, p4_up, p1_down, p2_down, p3_down,
p4_down, p1_left, p2_left, p3_left, p4_left, p1_right,
p2_right, p3_right, p4_right, p1_doubleright_up, p2_doubleright_up,
p3_doubleright_up, p4_doubleright_up, p1_doubleright_down,
p2_doubleright_down, p3_doubleright_down, p4_doubleright_down,
p1_doubleright_left, p2_doubleright_left, p3_doubleright_left,
p4_doubleright_left, p1_doubleright_right, p2_doubleright_right,
p3_doubleright_right, p4_doubleright_right, p1_doubleleft_up,
p2_doubleleft_up, p3_doubleleft_up, p4_doubleleft_up, p1_doubleleft_down,
p2_doubleleft_down, p3_doubleleft_down, p4_doubleleft_down,
p1_doubleleft_left, p2_doubleleft_left, p3_doubleleft_left,
p4_doubleleft_left, p1_doubleleft_right, p2_doubleleft_right,
p3_doubleleft_right, p4_doubleleft_right, p1_button1, p2_button1,
p3_button1, p4_button1, p1_button2, p2_button2, p3_button2,
p4_button2, p1_button3, p2_button3, p3_button3, p4_button3,
p1_button4, p2_button4, p3_button4, p4_button4, p1_button5,
p2_button5, p3_button5, p4_button5, p1_button6, p2_button6,
p3_button6, p4_button6, p1_button7, p2_button7, p3_button7,
p4_button7, p1_button8, p2_button8, p3_button8, p4_button8,
p1_button9, p2_button9, p3_button9, p4_button9, p1_button10,
p2_button10, p3_button10, p4_button10, p1_paddle_left,
p1_paddle_right, p2_paddle_left, p2_paddle_right, p3_paddle_left,
p3_paddle_right, p4_paddle_left, p4_paddle_right, p1_paddle_up,
p1_paddle_down, p2_paddle_up, p2_paddle_down, p3_paddle_up,
p3_paddle_down, p4_paddle_up, p4_paddle_down, p1_stick_left,
p1_stick_right, p2_stick_left, p2_stick_right, p3_stick_left,
p3_stick_right, p4_stick_left, p4_stick_right, p1_stick_up,
p1_stick_down, p2_stick_up, p2_stick_down, p3_stick_up,
p3_stick_down, p4_stick_up, p4_stick_down, p1_stick_forward,
p1_stick_backward, p2_stick_forward, p2_stick_backward,
p3_stick_forward, p3_stick_backward, p4_stick_forward,
p4_stick_backward, p1_lightgun_left, p1_lightgun_right,
p2_lightgun_left, p2_lightgun_right, p3_lightgun_left,
p3_lightgun_right, p4_lightgun_left, p4_lightgun_right,
p1_lightgun_up, p1_lightgun_down, p2_lightgun_up, p2_lightgun_down,
p3_lightgun_up, p3_lightgun_down, p4_lightgun_up, p4_lightgun_down,
p1_pedalgas_push, p1_pedalgas_release, p2_pedalgas_push,
p2_pedalgas_release, p3_pedalgas_push, p3_pedalgas_release,
p4_pedalgas_push, p4_pedalgas_release, p1_pedalbrake_push,
p1_pedalbrake_release, p2_pedalbrake_push, p2_pedalbrake_release,
p3_pedalbrake_push, p3_pedalbrake_release, p4_pedalbrake_push,
p4_pedalbrake_release, p1_pedalother_push, p1_pedalother_release,
p2_pedalother_push, p2_pedalother_release, p3_pedalother_push,
p3_pedalother_release, p4_pedalother_push, p4_pedalother_release,
p1_dial_left, p1_dial_right, p2_dial_left, p2_dial_right,
p3_dial_left, p3_dial_right, p4_dial_left, p4_dial_right,
p1_dial_up, p1_dial_down, p2_dial_up, p2_dial_down, p3_dial_up,
p3_dial_down, p4_dial_up, p4_dial_down, p1_trackball_left,
p1_trackball_right, p2_trackball_left, p2_trackball_right,
p3_trackball_left, p3_trackball_right, p4_trackball_left,
p4_trackball_right, p1_trackball_up, p1_trackball_down,
p2_trackball_up, p2_trackball_down, p3_trackball_up, p3_trackball_down,
p4_trackball_up, p4_trackball_down, p1_mouse_left, p1_mouse_right,
p2_mouse_left, p2_mouse_right, p3_mouse_left, p3_mouse_right,
p4_mouse_left, p4_mouse_right, p1_mouse_up, p1_mouse_down,
p2_mouse_up, p2_mouse_down, p3_mouse_up, p3_mouse_down,
p4_mouse_up, p4_mouse_down, start1, start2, start3, start4,
coin1, coin2, coin3, coin4, coin5, coin6, coin7, coin8,
bill1, service_coin1, service_coin2, service_coin3, service_coin4,
service_coin5, service_coin6, service_coin7, service_coin8,
service, tilt, interlock, p1_start, p2_start, p3_start,
p4_start, p1_select, p2_select, p3_select, p4_select, ui_mode_next,
ui_mode_pred, ui_record_start, ui_record_stop, ui_turbo,
ui_cocktail, ui_help, ui_startup, ui_configure, ui_on_screen_display,
ui_pause, ui_reset_machine, ui_show_gfx, ui_frameskip_dec,
ui_frameskip_inc, ui_throttle, ui_show_fps, ui_snapshot,
ui_toggle_cheat, ui_home, ui_end, ui_up, ui_down, ui_left, ui_right,
ui_select, ui_cancel, ui_pan_up, ui_pan_down, ui_pan_left, ui_pan_right,
ui_show_profiler, ui_toggle_ui, ui_toggle_debug, ui_save_state,
ui_load_state, ui_add_cheat, ui_delete_cheat, ui_save_cheat,
ui_watch_value, ui_edit_cheat, ui_toggle_crosshair, safequit,
event1, event2, event3, event4, event5, event6, event7,
event8, event9, event10, event11, event12, event13, event14,
key_q, key_w, key_e, key_r, key_t, key_y, key_u, key_i,
key_o, key_p, key_a, key_s, key_d, key_f, key_g, key_h,
key_j, key_k, key_l, key_z, key_x, key_c, key_v, key_b,
key_n, key_m, key_pad_0, key_pad_1, key_pad_2, key_pad_3,
key_pad_4, key_pad_5, key_pad_6, key_pad_7, key_pad_8,
key_pad_9, key_pad_enter, key_pad_minus, key_pad_plus,
key_pad_slash, key_pad_colon, key_pad_diesis, key_pad_asterisk,
key_0, key_1, key_2, key_3, key_4, key_5, key_6, key_7,
key_8, key_9, key_esc, key_enter, key_backspace, key_tab,
key_space, key_ins, key_del, key_home, key_end, key_fctn,
key_restore, key_store, key_play, key_print, key_hold,
key_rew, key_record, key_break, key_graph, key_pause, key_menu,
key_stop, key_again, key_undo, key_move, key_copy, key_open,
key_edit, key_paste, key_find, key_cut, key_help, key_back,
key_forward, key_capslock, key_scrlock, key_numlock, key_quickload,
key_pgup, key_pgdn, key_backquote, key_minus, key_plus,
key_asterisk, key_equals, key_openbrace, key_closebrace,
key_semicolon, key_quote, key_backslash, key_less, key_comma,
key_period, key_slash, key_colon, key_pound, key_doublequote,
key_diesis, key_lshift, key_rshift, key_lctrl, key_rctrl,
key_lalt, key_ralt, key_ctrl, key_alt, key_shift, key_left,
key_right, key_up, key_down, key_f1, key_f2, key_f3, key_f4,
key_f5, key_f6, key_f7, key_f8, key_f9, key_f10, key_f11,
key_f12, key_f13, key_f14, key_f15, key_f16, key_f17, key_f18,
key_f19, key_f20, key_f21, key_f22, key_f23, key_f24.
.RE
.PP
Note that the p*_start, p*_select and key_* controls are avaiable
only in MESS.
.PP
The MOUSE_BUTTON names can be checked using the \(oqadvm\(cq utility.
Generally they are:
.RS 4
.PD 0
.HP 4
.I left, right, middle
Standard buttons.
.HP 4
.I side
Side button.
.HP 4
.I extra
Extra button.
.HP 4
.I forward
Forward button.
.HP 4
.I back
Back button.
.HP 4
.I fourth, fifth, sixth
Misc buttons.
.PD
.RE
.PP
The KEY names can be checked using the \(oqadvk\(cq utility.
Generally they are:
.PP
.RS 4
a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u,
v, w, x, y, z, n0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0_pad, 1_pad,
2_pad, 3_pad, 4_pad, 5_pad, 6_pad, 7_pad, 8_pad, 9_pad, f1, f2, f3,
f4, f5, f6, f7, f8, f9, f10, f11, f12, esc, backquote, minus,
equals, backspace, tab, openbrace, closebrace, enter, semicolon,
quote, backslash, less, comma, period, slash, space, insert,
del, home, end, pgup, pgdn, left, right, up, down, slash_pad, asterisk_pad,
minus_pad, plus_pad, period_pad, enter_pad, prtscr, pause, lshift,
rshift, lcontrol, rcontrol, lalt, ralt, lwin, rwin, menu, scrlock,
numlock, capslock, stop, again, props, undo, front, copy, open,
paste, find, cut, help, calc, setup, sleep, wakeup, file, sendfile,
deletefile, xfer, prog1, prog2, www, msdos, coffee, direction,
cyclewindows, mail, bookmarks, computer, back, forward, closecd,
ejectcd, ejectclosecd, nextsong, playpause, previoussong, stopcd,
record, rewind, phone, iso, config, homepage, refresh, exit,
move, edit, scrollup, scrolldown, leftparen_pad, rightparen_pad,
intl1, intl2, intl3, intl4, intl5, intl6, intl7, intl8, intl9,
lang1, lang2, lang3, lang4, lang5, lang6, lang7, lang8, lang9,
playcd, pausecd, prog3, prog4, suspend, close, brightnessdown,
brightnessup, macro, mute, volumedown, volumeup, power, compose,
f13, f14, f15, f16, f17, f18, f19, f20, f21, f22, f23, f24.
.RE
.PP
You can also specify a numerical scancode N in the form: \(oqscanN\(cq.
.PP
The JOY_BUTTON button names can be checked using the \(oqadvj\(cq utility.
Generally they are:
.RS 4
.PD 0
.HP 4
.I trigger
Joystick trigger button.
.HP 4
.I top, top2
Joystick top buttons.
.HP 4
.I thumb, thumb2
Joystick thumb buttons.
.HP 4
.I pinkie
Joystick pinkie button.
.HP 4
.I base, base2, base3, base4, base5, base6
Joystick base buttons.
.HP 4
.I dead
Joystick dead button.
.HP 4
.I a, b, c, x, y, z
GamePad buttons.
.HP 4
.I tl, tr, tl2, tr2
GamePad top (left/right) buttons.
.HP 4
.I thumbl thumbr
GamePad thumb (left/right) buttons.
.HP 4
.I select, start, mode
GamePad extra buttons.
.HP 4
.I gear_up, gear_down
Wheel gear buttons.
.HP 4
.I left, right, middle
Ball standard buttons.
.HP 4
.I side
Ball side button.
.HP 4
.I extra
Ball extra button.
.HP 4
.I forward
Ball forward button.
.HP 4
.I back
Ball back button.
.HP 4
.I fourth, fifth, sixth
Ball misc buttons.
.HP 4
.I 0, 1, 2, 3, 4, 5, 6, 7, 8, 9
Misc buttons.
.PD
.RE
.PP
Examples:
.PP
.RS 4
input_map[p1_left] keyboard[0,left] or joystick_digital[0,stick,x,left]
.PD 0
.PP
.PD
input_map[p1_right] keyboard[0,right] or joystick_digital[0,stick,x,right]
.PD 0
.PP
.PD
input_map[p1_button1] keyboard[0,lshit] or joystick_button[0,trigger]
.PD 0
.PP
.PD
.RE
.SS input_name 
Changes the display name of the specified digital input.
.PP
input_name (keyboard[KEYBOARD,KEY]
.PD 0
.PP
.PD
	| mouse_button[MOUSE,MOUSE_BUTTON]
.PD 0
.PP
.PD
	| joystick_button[JOY,JOY_BUTTON]
.PD 0
.PP
.PD
	| joystick_digital[JOY,CONTROL,AXE,DIR])
.PD 0
.PP
.PD
	NAME
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I KEY
Name of physical key.
.HP 4
.I MOUSE
Number of physical mouse: 0, 1, 2, 3, ...
.HP 4
.I MOUSE_BUTTON
Number or name of a physical mouse button:
0, 1, 2, 3, ...
.HP 4
.I JOY
Number of physical joystick: 0, 1, 2, 3, ...
.HP 4
.I CONTROL
Number or name of physical control of the joystick: 0, 1, 2, 3, ...
.HP 4
.I DIR
Direction of the movement: left, up, right, down.
.HP 4
.I AXE
Number or name of physical axe of the control: 0, 1, 2, 3, ...
.HP 4
.I JOY_BUTTON
Number or name of a physical joystick button:
0, 1, 2, 3, ...
.HP 4
.I NAME
Display name for digital input.
.PD
.RE
.PP
See input_map for valid KEY, MOUSE_BUTTON, CONTROL, JOY_BUTTON names.
.PP
Examples:
.PP
.RS 4
input_name keyboard[0,lcontrol] Blue
.PD 0
.PP
.PD
input_name joystick_digital[0,stick,x,right] Right
.PD 0
.PP
.PD
.RE
.SS input_setting[*] 
Selects some additional settings for analog inputs. These
settings can be modified using the \(a"Analog Config\(a" menu
present if the game has analog controls.
.PP
input_setting[NAME] SETTING
.PD 0
.PP
.PD
.SS input_dipswitch[*] 
Selects the state of the game dipswitch. These settings can be
modified using the \(a"Dipswitch\(a" menu present if the game has
dipswitches.
.PP
input_dipswitch[NAME] SETTING
.PD 0
.PP
.PD
.SS input_configswitch[*] 
Selects the state of the game configswitch. These settings can
be modified using the \(a"Config\(a" menu present if the game has
configswitches.
.PP
input_configswitch[NAME] SETTING
.PD 0
.PP
.PD
.SS User Interface Configuration Options 
This section describes the options used to customize the user
interface.
.SS ui_helpimage 
Selects the image to display on help request. The image must be
a PNG file. The pixels in black are used as background, any other
color is used as foreground. Please note that the displayed image
is always black and white.
.PP
ui_helpimage auto | FILE
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I auto
Use the internal help image. With this option all the
ui_helptag options are ignored.
.HP 4
.I FILE
Load an arbitrary image from a file.
.PD
.RE
.PP
The data used for the default image is in the \(oqcontrib/help\(cq dir.
.SS ui_helptag 
Selects the highlight range for any digital input. When the user
press a key/button the related range is highlighted.
A different color for any player is used in the image.
.PP
ui_helptag (keyboard[KEYBOARD,KEY]
.PD 0
.PP
.PD
	| mouse_button[MOUSE,MOUSE_BUTTON]
.PD 0
.PP
.PD
	| joystick_button[JOY,JOY_BUTTON]
.PD 0
.PP
.PD
	| joystick_digital[JOY,CONTROL,AXE,DIR])
.PD 0
.PP
.PD
	X Y DX DY
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I keyboard/mouse_*/joystick_*
One digital input. Like the
input_map option.
.HP 4
.I X, Y
The upper/left position in the image of the input range.
.HP 4
.I DX, DY
The size in pixel of the input range.
.PD
.RE
.PP
Examples:
.PP
.RS 4
ui_helptag keyboard[0,esc] 6 5 12 12
.PD 0
.PP
.PD
ui_helptag keyboard[0,f1] 26 5 12 12
.PD 0
.PP
.PD
ui_helptag keyboard[0,f2] 38 5 12 12
.PD 0
.PP
.PD
ui_helptag keyboard[0,f3] 50 5 12 12
.PD 0
.PP
.PD
ui_helptag keyboard[0,f4] 62 5 12 12
.PD 0
.PP
.PD
ui_helptag keyboard[0,f5] 81 5 12 12
.PD 0
.PP
.PD
ui_helptag keyboard[0,f6] 93 5 12 12
.PD 0
.PP
.PD
ui_helptag keyboard[0,f7] 105 5 12 12
.PD 0
.PP
.PD
ui_helptag keyboard[0,f8] 117 5 12 12
.PD 0
.PP
.PD
ui_helptag keyboard[0,f9] 137 5 12 12
.PD 0
.PP
.PD
ui_helptag keyboard[0,f10] 149 5 12 12
.PD 0
.PP
.PD
.RE
.PP
The data used for the default image is in the \(oqcontrib/help\(cq dir.
.SS ui_font 
Selects a font file. The formats TrueType (TTF), GRX, PSF and
RAW are supported. You can find a collection of fonts in the
\(oqcontrib\(cq directory.
.PP
ui_font auto | \(a"FILE\(a"
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I auto
Use the built\(hyin font (default).
.HP 4
.I FILE
Font file path.
.PD
.RE
.PP
The TrueType (TTF) format is supported only if the program is
compiled with the FreeType2 library.
.SS ui_fontsize 
Selects the font size, if the specified font is scalable.
The size is expressed in number of rows and columns of text in the
screen.
.PP
ui_fontsize auto | ROWS [COLS]
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I auto
Automatically compute the size (default).
.HP 4
.I ROWS
Number of text rows.
.HP 4
.I COLS
Number of text columns. If omitted, it\(cqs computed from
the number of rows.
.PD
.RE
.SS ui_color[*] 
Selects the user interface colors.
.PP
ui_color[TAG] FOREGROUND BACKGROUND
.PP
Tags:
.RS 4
.PD 0
.HP 4
.I interface
Main inteface color.
.HP 4
.I tag
Highlight tags.
.HP 4
.I select
Selected menu entries.
.HP 4
.I help_p1
Help color for player 1 controls.
.HP 4
.I help_p2
Help color for player 2 controls.
.HP 4
.I help_p3
Help color for player 3 controls.
.HP 4
.I help_p4
Help color for player 4 controls.
.HP 4
.I help_other
Help color for other controls
.PD
.RE
.PP
Options:
.RS 4
.PD 0
.HP 4
.I FOREGROUND
Foreground color in RRGGBB
hex format. For example FF0000 is red
and 00FF00 is green.
.HP 4
.I BACKGROUND
Background color. Like foreground color.
.PD
.RE
.SS ui_translucency 
Selects the translucency of the user interface.
.PP
ui_translucency FACTOR
.PP
Options:
.RS 4
.PD 0
.HP 4
.I FACTOR
Translucency factor from 0 to 1
(default 0.8).
.PD
.RE
.PP
The translucency ha no effect on the 8 bits palettized video
modes.
.SS Record Configuration Options 
This section describes the options used for the recording
features.
.PP
To start the recording press \(oqleft_ctrl+enter\(cq. To end the
recording and to save the clip press \(oqenter\(cq. If you press the
start key more than one time the recording starts from the
last press.
.SS record_sound 
Enables or disables the sound recording.
.PP
record_sound yes | no
.PD 0
.PP
.PD
.PP
The sound clip is saved in the \(oqdir_snap\(cq directory (like the
snapshot images) in \(oq.wav\(cq format. Specifically the \(oqWAV PCM
16 bit\(cq format is used. The sample rate used is the same sample
rate specified with the \(oqsound_samplerate\(cq option.
.PP
The clip is saved without compression and without any volume
adjustment. You should use an external utility to adjust the
volume and compress the resulting file.
.SS record_video 
Enables or disables the video recording.
.PP
record_video yes | no
.PD 0
.PP
.PD
.PP
The video clip is saved in the \(oqdir_snap\(cq directory (like the
snapshot images) in \(oq.mng\(cq format. The \(oqMNG\(hyLC\(cq (Low Complexity)
subformat is used.
.PP
The clip is saved with a lite compression, you should use an
external utility to compress better the resulting file.
.PP
A powerful compression utility is the \(oqadvmng\(cq program
available in the AdvanceCOMP package.
.SS record_video/sound_time 
Controls the maximum length in seconds of the recording feature.
.PP
record_sound_time TIME
.PD 0
.PP
.PD
record_video_time TIME
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I TIME
Time in seconds (default 15).
.PD
.RE
.SS record_video_interleave 
Selects how many frames to save with the video recording.
.PP
record_video_interleave COUNT
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I COUNT
How many frames displayed a frame must be saved
(default 2). 1 means save all the frames. 2
means save 1 every 2. 3 means save 1 every 3,
and so on.
.PD
.RE
.PP
Examples:
.PP
.RS 4
record_video_interleave 1
.PD 0
.PP
.PD
.RE
.SS Synchronization Options 
This section describes the options used for the time synchronization
of the emulated game or system.
.SS sync_fps 
Selects an arbitrary frame rate for the game.
.PP
sync_fps auto | FPS
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I auto
Use the original framerate of the game (default).
.HP 4
.I FPS
Use the specified framerate.
.PD
.RE
.SS sync_speed 
Selects a speed factor always active. You can play the game
in slowdown or in nightmare mode!
.PP
sync_speed FACTOR
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I FACTOR
Float speed factor (default 1.0).
.PD
.RE
.PP
Examples:
.PP
.RS 4
sync_speed 1.2
.PD 0
.PP
.PD
.RE
.SS sync_turbospeed 
Selects the speed factor used when the \(oqturbo\(cq button is
pressed. The default \(oqturbo\(cq key is \(oqasterisk_pad\(cq.
.PP
sync_turbospeed FACTOR
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I FACTOR
Float speed factor (default 3.0).
.PD
.RE
.SS sync_startuptime 
Selects the time in seconds of the duration of the startup
speed up. You can press the \(oqstartup\(cq key to save the current
game time as startup time. The default \(oqstartup\(cq key
is \(oqminus_pad\(cq.
.PP
sync_startuptime auto | none | TIME
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I auto
Get the value for the current game from
an internal database (default).
.HP 4
.I none
Disable the startup.
.HP 4
.I TIME
Time in seconds.
.PD
.RE
.SS sync_resample 
Selects the audio resampling mode.
.PP
sync_resample auto | emulation | internal
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I auto
Select automatically, at present it\(cqs always
the \(oqinternal\(cq mode (default).
.HP 4
.I emulation
Change the emulation to produce the requested
number of samples instead of resampling.
.HP 4
.I internal
Internally resample the sound to match the
current speed.
.PD
.RE
.PP
Note that the \(oqemulation\(cq mode may result in wrong input recording
using the \(oq\(hyrecord\(cq or \(oq\(hyplayback\(cq command line option due incorrect
behavior of the emulation. Specifically some implementations may
depend on the number of audio sample requested, information that
is not stored in the recorded input file.
.PP
Also, the \(oqemulation\(cq mode may trigger some bugs in the MAME
core.
.PP
Anyway, the \(oqemulation\(cq mode generates more stable sound
if the CPU load isn\(cqt totally empty.
.SS LCD Configuration Options 
AdvanceMAME is able to display arbitrary information on a LCD display
using the integrated script capabilities.
.PP
To use the LCD support you must install on your system the \(oqlcdproc\(cq
program available at:
.PP
.RS 4
http://lcdproc.sourceforge.net/
.PD 0
.PP
.PD
.RE
.PP
More details and some examples of how to display information on the LCD
using the scripts are in the \(oqscript.txt\(cq documentation file.
.SS lcd_server 
Selects the server address and port to use for display information on
the LCD.
.PP
lcd_server none | [SERVER][:PORT]
.PP
Options:
.RS 4
.PD 0
.HP 4
.I none
Disable the LCD support (default).
.HP 4
.I SERVER
Address of the server. If omitted \(oqlocalhost\(cq is used.
.HP 4
.I PORT
Port of the server. If omitted \(oq13666\(cq is used.
.PD
.RE
.PP
Examples:
.PP
.RS 4
lcd_server localhost
.PD 0
.PP
.PD
.RE
.SS lcd_timeout 
Selects the timeout to connect at the server.
.PP
lcd_timeout TIMEOUT
.PP
Options:
.RS 4
.PD 0
.HP 4
.I TIMEOUT
Timeout in milliseconds (default 500).
.PD
.RE
.SS lcd_speed 
Selects the LCD scrolling speed for long messages.
.PP
lcd_speed DELAY
.PP
Options:
.RS 4
.PD 0
.HP 4
.I DELAY
Delay in 1/8th of seconds (default 8).
.PD
.RE
.SS Misc Configuration Options 
.SS misc_bios 
Selects the game bios in AdvanceMAME.
.PP
misc_bios default | NAME
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I default
Use the default BIOS.
.HP 4
.I NAME
Select specific BIOS.
.PD
.RE
.SS misc_ramsize 
Controls the ram size of the emulated machine in AdvanceMESS.
.PP
misc_ramsize auto | SIZE [k|M|G]
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I auto
Automatic (default).
.HP 4
.I SIZE
Size of the RAM in bytes. You can use the \(cqk\(cq (1024),
\(cqM\(cq (1024^2) or \(cqG\(cq (1024^3) multiplier.
.PD
.RE
.PP
Examples:
.PP
.RS 4
misc_ramsize 1024k
.PD 0
.PP
.PD
.RE
.SS misc_difficulty 
Selects the game difficulty. This option works only with games
which select difficulty with dipswitches.
.PP
misc_difficulty none | easiest | easy | normal | hard | hardest
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I none
Don\(cqt change the default difficulty (default).
.HP 4
.I easiest
Easiest game play.
.HP 4
.I easy
Easy game play.
.HP 4
.I normal
Normal game play.
.HP 4
.I hard
Hard game play.
.HP 4
.I hardest
Hardest game play.
.PD
.RE
.SS misc_freeplay 
Selects the freeplay mode if the game support it. This
option works only with games that select the freeplay mode
with dipswitches.
.PP
misc_freeplay yes | no
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I no
Don\(cqt change the default mode (default).
.HP 4
.I yes
Activate the freeplay.
.PD
.RE
.SS misc_mutedemo 
Selects the demo nosound mode if the game support it. This
option uses the dipswitches of the game and also the
event database to detect if the game is in demo mode.
.PP
misc_mutedemo yes | no
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I no
Don\(cqt change the default mode (default).
.HP 4
.I yes
Mute the demo sounds.
.PD
.RE
.SS misc_lang 
Selects the game language and country. This option uses
both the dipswitches and the clones description to select
the correct game to run.
.PP
misc_lang none | usa | canada | englang | italy | germany
.PD 0
.PP
.PD
	| spain | austria | norway | france | denmark
.PD 0
.PP
.PD
	| japan | korea | china | hongkong | taiwan
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I none
Don\(cqt change the language (default).
.HP 4
.I LANG
If available select this language.
.PD
.RE
.PP
For example if you run \(oqcadash\(cq with \(oq\(hylang italy\(cq it\(cqs
run the clone \(oqcadashi\(cq. If you run \(oqcheesech\(cq with
\(oq\(hylang germany\(cq it\(cqs run \(oqcheesech\(cq setting the \(oqLanguage\(cq
dipswitch to \(oqGerman\(cq.
.PP
If the specified language is not available, european and
american languages fallback to english language.
Asian languages fallback to japanese language.
.PP
A game clone is selected only if it\(cqs a perfectly working
clone.
.SS misc_smp 
Enables the \(a"Symmetric Multi\(hyProcessing\(a" (SMP).
This option uses two concurrent threads. One for MAME and one
for updating the screen.
The final blit stage in video memory is completely done by the
second thread. This behavior requires a complete bitmap redraw
by MAME for the games that don\(cqt already do it.
Generally you get a big speed improvement only if you are using
a heavy video effect like \(oqhq\(cq and \(oqxbr\(cq.
.PP
misc_smp yes | no
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I no
Disabled (default).
.HP 4
.I yes
Enabled.
.PD
.RE
.PP
You can enable or disable it also on the runtime Video menu.
.SS misc_quiet 
Doesn\(cqt print the copyright text message at the startup, the
disclaimer and the generic game information screens.
.PP
misc_quiet yes | no
.PD 0
.PP
.PD
.SS misc_timetorun 
Run the emulation only for the given number of seconds without
any throttling and at the exit print the number of real CPU
seconds used. Useful for benchmarking.
.PP
misc_timetorun SECONDS
.PD 0
.PP
.PD
.SS Support Files Configuration Options 
The AdvanceMAME emulator can use also some support files:
.RS 4
.PD 0
.HP 4
.I event.dat
The Event and Safequit database.
.HP 4
.I cheat.dat
Cheat database.
.HP 4
.I hiscore.dat
Highscore database.
.HP 4
.I sysinfo.dat
MESS info database.
.HP 4
.I english.lng
Language database.
.PD
.RE
.PP
These files should reside in current directory for
DOS and Windows or in the $data or $home directories
for Linux a Mac OS X.
.SS misc_cheat 
Enables or disables the cheat system. It may also change the
game behavior enabling the cheat dip\(hyswitch if available.
If enabled, it disables the hiscore saving.
.PP
misc_cheat yes | no
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I yes
Enable the cheats.
.HP 4
.I no
Disable the cheats (default).
.PD
.RE
.SS misc_cheatfile 
Selects the cheat files. In DOS and Windows use the
\(oq;\(cq char as file separator. In Linux and Mac OS X use
the \(oq:\(cq char.
.PP
misc_cheatfile FILE[;FILE]... (DOS, Windows)
.PD 0
.PP
.PD
misc_cheatfile FILE[:FILE]... (Linux, Mac OS X)
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I FILE
Cheat file to load (default cheat.dat).
.PD
.RE
.SS misc_languagefile 
Selects the language file.
.PP
misc_languagefile FILE
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I FILE
Language file to load (default english.lng).
.PD
.RE
.SS misc_hiscorefile 
Selects the hiscore file.
.PP
misc_hiscorefile FILE
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I FILE
High score file to load (default hiscore.dat).
.PD
.RE
.SS misc_safequit 
Activates safe quit mode. If enabled, to stop the
emulation, you need to confirm on a simple menu.
.PP
misc_safequit yes | no
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I no
Disabled.
.HP 4
.I yes
Enabled (default).
.PD
.RE
.PP
If the file \(oqevent.dat\(cq (specified with the \(oqmisc_eventfile\(cq
option) is found the exit menu is shown only
if one or more coins are inserted or if you are playing.
.SS misc_eventdebug 
Activates the debug mode for the event/safequit feature. On the top
left of the screen the internal state of the event/safequit engine
is printed. The first value is the coin state, the second value
is the playing state. If both the values are 1 the exit is permitted
without prompting. Other values are the 6 generic events.
.PP
misc_eventdebug yes | no
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I no
Disabled (default).
.HP 4
.I yes
Enabled.
.PD
.RE
.SS misc_eventfile 
Selects the event/safequit database to use.
.PP
misc_eventfile FILE
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I FILE
Event file to load (default event.dat).
.PD
.RE
.SS Debugging Configuration Options 
The use of these options is discouraged. They are present only
for testing purpose.
.SS debug_crash 
Crashes the program. It can be used to ensure that the correct
video mode is restored on aborting conditions.
.PP
debug_crash yes | no
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I no
Don\(cqt crash the program (default).
.HP 4
.I yes
Add a \(a"Crash\(a" menu entry in the video menu.
If selected the program crash with a Segmentation
Fault.
.PD
.RE
.SS debug_rawsound 
Disables the sound output syncronization with the video.
.PP
debug_rawsound yes | no
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I no
Normal operation (default).
.HP 4
.I yes
Sound output without any syncronization.
.PD
.RE
.SS debug_speedmark 
Enables or disabled the on screen speed mark. If enabled a red square
is displayed if the game is too slow. A red triangle when you press
the \(oqturbo\(cq key or when the game is accelerated for other reasons.
.PP
debug_speedmark yes | no
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I yes
Display the speed mark when required.
.HP 4
.I no
Don\(cqt display the speed mark (default).
.PD
.RE
.SH SIGNALS 
The program intercepts the following signals:
.RS 4
.PD 0
.HP 4
.I SIGQUIT
Exit normally.
.HP 4
.I SIGTERM, SIGINT, SIGALRM
Exit restoring only the output devices.
.HP 4
.I SIGHUP
Restart the program.
.PD
.RE
.SH COPYRIGHT 
This file is Copyright (C) 2003, 2004, 2005 Andrea Mazzoleni, Filipe Estima.
