.TH "AdvanceMAME Sound Tester" 1
.SH NAME
advs \(hy AdvanceMAME Sound Tester
.SH SYNOPSIS 
advs [\(hydevice_sound DEVICE] [\(hysound_samplerate RATE]
.PD 0
.PP
.PD
	[\(hysound_latency TIME] [\(hysound_buffer TIME]
.PD 0
.PP
.PD
	[\(hysound_volume VOLUME] [\(hylog] [\(hylogsync]
.PD 0
.PP
.PD
	FILES...
.PD 0
.PP
.PD
.SH DESCRIPTION 
The \(oqadvs\(cq plays the specified wav and mp3 files.
If you specify more than one file all the files are mixed
and played together.
.PP
Press Break to terminate before the end.
.PP
Check the \(oqadvdev.txt\(cq file for the description of
the \(oqdevice_sound\(cq option.
.SH COPYRIGHT 
This file is Copyright (C) 2003 Andrea Mazzoleni.
