#include "pci_ids.h"

/* aty128fb.c */
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RAGE128_RE, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RAGE128_RF, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RAGE128_RK, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RAGE128_RL, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RAGE128_PF, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RAGE128_PR, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RAGE128_U3, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RAGE128_U1, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RAGE128_LE, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RAGE128_LF, "" },

/* neofb.c */
#define PCI_CHIP_NM2070 0x0001
#define PCI_CHIP_NM2090 0x0002
#define PCI_CHIP_NM2093 0x0003
#define PCI_CHIP_NM2097 0x0083
#define PCI_CHIP_NM2160 0x0004
#define PCI_CHIP_NM2200 0x0005
#define PCI_CHIP_NM2230 0x0025
#define PCI_CHIP_NM2360 0x0006
#define PCI_CHIP_NM2380 0x0016

{ PCI_VENDOR_ID_NEOMAGIC, PCI_CHIP_NM2070, "" },
{ PCI_VENDOR_ID_NEOMAGIC, PCI_CHIP_NM2090, "" },
{ PCI_VENDOR_ID_NEOMAGIC, PCI_CHIP_NM2093, "" },
{ PCI_VENDOR_ID_NEOMAGIC, PCI_CHIP_NM2097, "" },
{ PCI_VENDOR_ID_NEOMAGIC, PCI_CHIP_NM2160, "" },
{ PCI_VENDOR_ID_NEOMAGIC, PCI_CHIP_NM2200, "" },
{ PCI_VENDOR_ID_NEOMAGIC, PCI_CHIP_NM2230, "" },
{ PCI_VENDOR_ID_NEOMAGIC, PCI_CHIP_NM2360, "" },
{ PCI_VENDOR_ID_NEOMAGIC, PCI_CHIP_NM2380, "" },

/* pm2fb.c */
/* { PCI_VENDOR_ID_TI, PCI_DEVICE_ID_TI_TVP4020, "" }, */ /* too old to list */
{ PCI_VENDOR_ID_3DLABS, PCI_DEVICE_ID_3DLABS_PERMEDIA2, "" },
{ PCI_VENDOR_ID_3DLABS, PCI_DEVICE_ID_3DLABS_PERMEDIA2V, "" },

/* pm3fb.c */
#define PCI_DEVICE_ID_3DLABS_PERMEDIA3 0x000a

{ PCI_VENDOR_ID_3DLABS, PCI_DEVICE_ID_3DLABS_PERMEDIA3, "" },

/* radeonfb.c */
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_QD, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_QE, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_QF, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_QG, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_QY, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_QZ, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_LW, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_LX, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_LY, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_LZ, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_QL, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_QN, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_QO, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_Ql, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_BB, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_QM, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_QW, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_QX, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_Id, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_Ie, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_If, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_Ig, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_Ld, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_Le, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_Lf, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_Lg, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_ND, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_NF, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_NG, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_AE, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_AF, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_NH, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_NI, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_Y_, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_AD, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_AP, "" },
{ PCI_VENDOR_ID_ATI, PCI_DEVICE_ID_ATI_RADEON_AR, "" },

/* tdfxfb.c */
#define PCI_DEVICE_ID_3DFX_VOODOO5	0x0009
{ PCI_VENDOR_ID_3DFX, PCI_DEVICE_ID_3DFX_BANSHEE, "" },
{ PCI_VENDOR_ID_3DFX, PCI_DEVICE_ID_3DFX_VOODOO3, "" },
{ PCI_VENDOR_ID_3DFX, PCI_DEVICE_ID_3DFX_VOODOO5, "" },

/* tridentfb.c */
#define CYBER9320	0x9320
#define CYBER9388	0x9388
#define CYBER9382	0x9382
#define CYBER9385	0x9385
#define CYBER9397	0x9397
#define CYBER9397DVD	0x939A
#define CYBER9520	0x9520
#define CYBER9525DVD	0x9525
#define TGUI9660	0x9660
#define IMAGE975	0x9750
#define IMAGE985	0x9850
#define BLADE3D		0x9880
#define CYBERBLADEE4	0x9540
#define CYBERBLADEi7	0x8400
#define CYBERBLADEi7D	0x8420
#define CYBERBLADEi1	0x8500
#define CYBERBLADEi1D	0x8520
#define CYBERBLADEAi1	0x8600
#define CYBERBLADEAi1D	0x8620
#define CYBERBLADEXPAi1 0x8820
#define CYBERBLADEXPm8  0x9910
#define CYBERBLADEXPm16 0x9930

{ PCI_VENDOR_ID_TRIDENT, BLADE3D, "" },
{ PCI_VENDOR_ID_TRIDENT, CYBERBLADEi7, "" },
{ PCI_VENDOR_ID_TRIDENT, CYBERBLADEi7D, "" },
{ PCI_VENDOR_ID_TRIDENT, CYBERBLADEi1, "" },
{ PCI_VENDOR_ID_TRIDENT, CYBERBLADEi1D, "" },
{ PCI_VENDOR_ID_TRIDENT, CYBERBLADEAi1, "" },
{ PCI_VENDOR_ID_TRIDENT, CYBERBLADEAi1D, "" },
{ PCI_VENDOR_ID_TRIDENT, CYBERBLADEE4, "" },
{ PCI_VENDOR_ID_TRIDENT, TGUI9660, "" },
{ PCI_VENDOR_ID_TRIDENT, IMAGE975, "" },
{ PCI_VENDOR_ID_TRIDENT, IMAGE985, "" },
{ PCI_VENDOR_ID_TRIDENT, CYBER9320, "" },
{ PCI_VENDOR_ID_TRIDENT, CYBER9388, "" },
{ PCI_VENDOR_ID_TRIDENT, CYBER9520, "" },
{ PCI_VENDOR_ID_TRIDENT, CYBER9525DVD, "" },
{ PCI_VENDOR_ID_TRIDENT, CYBER9397, "" },
{ PCI_VENDOR_ID_TRIDENT, CYBER9397DVD, "" },
{ PCI_VENDOR_ID_TRIDENT, CYBERBLADEXPAi1, "" },
{ PCI_VENDOR_ID_TRIDENT, CYBERBLADEXPm8, "" },
{ PCI_VENDOR_ID_TRIDENT, CYBERBLADEXPm16, "" },
 
/* intelfb.c */
#define PCI_DEVICE_ID_INTEL_830M	0x3577
#define PCI_DEVICE_ID_INTEL_845G	0x2562
#define PCI_DEVICE_ID_INTEL_85XGM	0x3582
#define PCI_DEVICE_ID_INTEL_865G	0x2572

{ PCI_VENDOR_ID_INTEL, PCI_DEVICE_ID_INTEL_830M, "" },
{ PCI_VENDOR_ID_INTEL, PCI_DEVICE_ID_INTEL_845G, "" },
{ PCI_VENDOR_ID_INTEL, PCI_DEVICE_ID_INTEL_85XGM, "" },
{ PCI_VENDOR_ID_INTEL, PCI_DEVICE_ID_INTEL_865G, "" },

/* matroxfb_base */
{ PCI_VENDOR_ID_MATROX, PCI_DEVICE_ID_MATROX_MIL, "" },
{ PCI_VENDOR_ID_MATROX, PCI_DEVICE_ID_MATROX_MIL_2, "" },
{ PCI_VENDOR_ID_MATROX, PCI_DEVICE_ID_MATROX_MIL_2_AGP, "" },
{ PCI_VENDOR_ID_MATROX, PCI_DEVICE_ID_MATROX_MYS, "" },
{ PCI_VENDOR_ID_MATROX, PCI_DEVICE_ID_MATROX_G100_MM, "" },
{ PCI_VENDOR_ID_MATROX, PCI_DEVICE_ID_MATROX_G100_AGP, "" },
{ PCI_VENDOR_ID_MATROX, PCI_DEVICE_ID_MATROX_G200_PCI, "" },
{ PCI_VENDOR_ID_MATROX, PCI_DEVICE_ID_MATROX_G200_AGP, "" },
{ PCI_VENDOR_ID_MATROX, PCI_DEVICE_ID_MATROX_G400, "" },
{ PCI_VENDOR_ID_MATROX, PCI_DEVICE_ID_MATROX_G550, "" },

/* rivafb.c */
/* { PCI_VENDOR_ID_NVIDIA_SGS, PCI_DEVICE_ID_NVIDIA_SGS_RIVA128, "" }, */ /* too old to list */
{ PCI_VENDOR_ID_NVIDIA, PCI_DEVICE_ID_NVIDIA_TNT, "" },
{ PCI_VENDOR_ID_NVIDIA, PCI_DEVICE_ID_NVIDIA_TNT2, "" },
{ PCI_VENDOR_ID_NVIDIA, PCI_DEVICE_ID_NVIDIA_UTNT2, "" },
{ PCI_VENDOR_ID_NVIDIA, PCI_DEVICE_ID_NVIDIA_VTNT2, "" },
{ PCI_VENDOR_ID_NVIDIA, PCI_DEVICE_ID_NVIDIA_UVTNT2, "" },
{ PCI_VENDOR_ID_NVIDIA, PCI_DEVICE_ID_NVIDIA_ITNT2, "" },
{ PCI_VENDOR_ID_NVIDIA, PCI_DEVICE_ID_NVIDIA_GEFORCE_SDR, "" },
{ PCI_VENDOR_ID_NVIDIA, PCI_DEVICE_ID_NVIDIA_GEFORCE_DDR, "" },
{ PCI_VENDOR_ID_NVIDIA, PCI_DEVICE_ID_NVIDIA_QUADRO, "" },
{ PCI_VENDOR_ID_NVIDIA, PCI_DEVICE_ID_NVIDIA_GEFORCE2_MX, "" },
{ PCI_VENDOR_ID_NVIDIA, PCI_DEVICE_ID_NVIDIA_GEFORCE2_MX2, "" },
{ PCI_VENDOR_ID_NVIDIA, PCI_DEVICE_ID_NVIDIA_QUADRO2_MXR, "" },
{ PCI_VENDOR_ID_NVIDIA, PCI_DEVICE_ID_NVIDIA_GEFORCE2_GTS, "" },
{ PCI_VENDOR_ID_NVIDIA, PCI_DEVICE_ID_NVIDIA_GEFORCE2_GTS2, "" },
{ PCI_VENDOR_ID_NVIDIA, PCI_DEVICE_ID_NVIDIA_GEFORCE2_ULTRA, "" },
{ PCI_VENDOR_ID_NVIDIA, PCI_DEVICE_ID_NVIDIA_QUADRO2_PRO, "" },
{ PCI_VENDOR_ID_NVIDIA, PCI_DEVICE_ID_NVIDIA_GEFORCE2_GO, "" },
{ PCI_VENDOR_ID_NVIDIA, PCI_DEVICE_ID_NVIDIA_GEFORCE3, "" },
{ PCI_VENDOR_ID_NVIDIA, PCI_DEVICE_ID_NVIDIA_GEFORCE3_1, "" },
{ PCI_VENDOR_ID_NVIDIA, PCI_DEVICE_ID_NVIDIA_GEFORCE3_2, "" },
{ PCI_VENDOR_ID_NVIDIA, PCI_DEVICE_ID_NVIDIA_QUADRO_DDC, "" },

/* i810_main.h 23 */
#define PCI_DEVICE_ID_INTEL_82810_MC4           0x7124
#define PCI_DEVICE_ID_INTEL_82810_IG4           0x7125
#define PCI_DEVICE_ID_INTEL_82815_100           0x1102
#define PCI_DEVICE_ID_INTEL_82815_NOAGP         0x1112
#define PCI_DEVICE_ID_INTEL_82815_FULL_CTRL     0x1130
#define PCI_DEVICE_ID_INTEL_82815_FULL_BRG      0x1131
#define PCI_DEVICE_ID_INTEL_82815_FULL          0x1132

{ PCI_VENDOR_ID_INTEL, PCI_DEVICE_ID_INTEL_82810_IG1, "" },
{ PCI_VENDOR_ID_INTEL, PCI_DEVICE_ID_INTEL_82810_IG3, "" },
{ PCI_VENDOR_ID_INTEL, PCI_DEVICE_ID_INTEL_82810_IG4, "" },
{ PCI_VENDOR_ID_INTEL, PCI_DEVICE_ID_INTEL_82815_100, "" },
{ PCI_VENDOR_ID_INTEL, PCI_DEVICE_ID_INTEL_82815_NOAGP, "" },
{ PCI_VENDOR_ID_INTEL, PCI_DEVICE_ID_INTEL_82815_FULL, "" },

/* sstfb.c */
{ PCI_VENDOR_ID_3DFX, PCI_DEVICE_ID_3DFX_VOODOO, "" },
{ PCI_VENDOR_ID_3DFX, PCI_DEVICE_ID_3DFX_VOODOO2, "" },

/* sis/vesafb */
/* They don't allwo to set an arbitrary video mode */

/* clgenfb.c */
{ PCI_VENDOR_ID_CIRRUS, PCI_DEVICE_ID_CIRRUS_5436, "" },
{ PCI_VENDOR_ID_CIRRUS, PCI_DEVICE_ID_CIRRUS_5434_8, "" },
{ PCI_VENDOR_ID_CIRRUS, PCI_DEVICE_ID_CIRRUS_5434_4, "" },
{ PCI_VENDOR_ID_CIRRUS, PCI_DEVICE_ID_CIRRUS_5430, "" },
{ PCI_VENDOR_ID_CIRRUS, PCI_DEVICE_ID_CIRRUS_7543, "" },
{ PCI_VENDOR_ID_CIRRUS, PCI_DEVICE_ID_CIRRUS_7548, "" },
{ PCI_VENDOR_ID_CIRRUS, PCI_DEVICE_ID_CIRRUS_5480, "" },
{ PCI_VENDOR_ID_CIRRUS, PCI_DEVICE_ID_CIRRUS_5446, "" },
{ PCI_VENDOR_ID_CIRRUS, PCI_DEVICE_ID_CIRRUS_5462, "" },
{ PCI_VENDOR_ID_CIRRUS, PCI_DEVICE_ID_CIRRUS_5464, "" },
{ PCI_VENDOR_ID_CIRRUS, PCI_DEVICE_ID_CIRRUS_5465, "" },

#define PCI_VENDOR_ID_VMWARE        0x15AD
#define PCI_DEVICE_ID_VMWARE_SVGA2  0x0405
#define PCI_DEVICE_ID_VMWARE_SVGA   0x0710

/* vmwarefb */
{ PCI_VENDOR_ID_VMWARE, PCI_DEVICE_ID_VMWARE_SVGA, "" },
{ PCI_VENDOR_ID_VMWARE, PCI_DEVICE_ID_VMWARE_SVGA2, "" },

/* cyber2000fb */
{ PCI_VENDOR_ID_INTERG, PCI_DEVICE_ID_INTERG_2000 , "" },
{ PCI_VENDOR_ID_INTERG, PCI_DEVICE_ID_INTERG_2010 , "" },
{ PCI_VENDOR_ID_INTERG, PCI_DEVICE_ID_INTERG_5000 , "" },

